### ISSUE TITLE
WebJob Deployed To Wrong Location When Web App Is In Virtual Directory

### ISSUE THREAD

**Issue by ghost** [projectkudu/kudu#2249] opened 2016-12-03 07:29 UTC
Hey folks.

I'm running into a deployment/portal issue with webjob associated with a web web app in a virtual directory.  The webjob gets deployed to wwwroot/virtualdir/app_data/...  and doesn't show up in the portal at all (this happens whether i publish manually through VS or let the git deployment handle it).

I have some webjobs created through the portal (uploaded zip) and these get saved to wwwroot/app_data/... and they show up in the portal.

So. Is the deployment wrong (a bug or an obvious config setting i've missed) or should the portal be showing the webjobs placed in the virtual directory locations? 

Here's my setup for the problematic webjobs

- Continuous (TimeTrigger)
- .NET console app with WebJobs SDK
- VS studio or git deploy

PS.  Thanks for all your hard work.

**Comment by davidebbo** [comment] 2016-12-03 19:56
From the point of view of the WebJobs runtime (implemented in Kudu), WebJobs are **always** under `d:\home\site\wwwroot\app_data\...`

So the issue is that the VS WebJobs publishing logic doesn't have proper support for deploying WebJobs when the app is going to a non-default folder. i.e. it always deploys the WebJobs under the web app's folder, even if it's not wwwroot.

Conceivably, we could support some Kudu setting that would change the location that WebJobs are in. e.g. you'd set something like `SCM_WEBJOBS_FOLDER=site/wwwroot/SomeDir/App_Data/jobs`, while the default would be `site/wwwroot/App_Data/jobs`.

**Comment by aramayowa** [comment] 2016-12-04 06:38
Thanks for getting back to me so quickly.

That ("the webjobs runtime only looking at d:\home\site\wwwroot\app_data\jobs\...) makes sense. I was under the impression that kudu was responsible for the deployment of the web job during a git deployment (I also get the same behavior here) which would mean both kudu (at the publish/deploy stage) and vs studio both don't handle the non default location well.

Creating a kudu setting is fine with me. Would that also make sure the portal is looking at this special location instead of the default?

Thanks again.

**Comment by davidebbo** [comment] 2016-12-05 00:05
Well, it's really neither VS nor Kudu that does this, but it's the msbuild project and target file that VS generates. Then whether you build deploy locally or build on Kudu, that takes effect, but Kudu itself has absolutely no idea what the deployment is creating. It's all msbuild.

Yes, if we do this right, it should correctly affect the portal. Marking this as Feature.

**Comment by aramayowa** [comment] 2016-12-06 01:04
> Well, it's really neither VS nor Kudu that does this, but it's the msbuild project and target file that VS generates. Then whether you build deploy locally or build on Kudu, that takes effect

Got it. Thank you for taking the time to explain.

> Yes, if we do this right, it should correctly affect the portal. Marking this as Feature.

Great. Looking forward to it.

Thanks for your help.

**Comment by jvano** [comment] 2024-04-29 10:20
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Closed by jvano** 2024-04-29 10:20 UTC
Labels: feature
