### ISSUE TITLE
App Settings "Project" variable seems to get "forgotten"

### ISSUE THREAD

**Issue by stevemurch** [projectkudu/kudu#1591] opened 2015-06-16 21:58 UTC
Hi all -- thanks for all the Kudu work everyone!
We have continuous deployment working for 1 solution, which contains 4 different web points of service (all sharing a common set of libraries).
Everything works fine, using the "Project=myproj\myproc.csproj" app setting.  Until, that is, it somehow and mysteriously gets "forgotten" (i.e., the Project variable is wiped out) by Azure for some unknown reason.  That is, the variable is completely wiped out, on both staging and production.  
Can you think of any reason for this?  It's a hassle to keep re-training it what the "Project" variables are.

I don't know if this is helpful, but I had previously tried to customize the script, but then eliminated that customization (including the .deployment and deploy.cmd files).

**Comment by ahmelsayed** [comment] 2015-06-17 17:14
are you setting it as an AppSetting from portal? Do you do any management operations on the site using PowerShell or other REST clients (C#, node, etc)? 

I am assuming all the app settings get wiped out, not just 'Project' right? one of the gotchas of the Azure Web Apps API is that anytime you need to add an extra app setting or update the config, you have to round trip the content, So you need to do a GET first and then do a PUT or POST or it'll overwrite all of your settings

**Comment by stevemurch** [comment] 2015-06-17 21:00
Thanks Ahmel for the response.  

Yes, I'm setting it as an AppSetting from the (new preview) Portal.  I do not do any management operations on the site via PowerShell.  (I did once try to customize the deployment to inject XUnit tests but I'm positive I've deleted the .deployment and deploy.cmd from the repository, and I'm pretty sure this problem occurred before I tried that.)

One other note -- it appears this might be happening only when a VIP swap is done (production <--> staging).  It basically completely "forgets" the Project setting on both production and staging.

No, all the other settings are preserved.

**Comment by ahmelsayed** [comment] 2015-06-17 21:03
That's pretty odd. Can you share the site name either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?

**Comment by stevemurch** [comment] 2015-06-17 21:22
Thanks much for the responsiveness.  I've created the following temp site for indirect identification:
temporaryid1000.azurewebsites.net

**Comment by ahmelsayed** [comment] 2015-06-19 21:18
Hi @stevemurch, sorry for the delay in getting back to you. We have a repro for the issue and Galin is taking a look at it. I know this isn't very helpful, but will let you know once we have updates.

/cc @galcho

**Comment by stevemurch** [comment] 2015-06-19 22:36
Thanks much.  It hasn't happened in the past two days (in fact our
continuous integration builds/deploys have been remarkably fast over the
past 48 hours).

**Comment by galcho** [comment] 2015-06-23 00:53
@stevemurch the issue happens via the new portal. If you setup via old portal all should be fine (it is RBAC related).
the fix will be in the next roll out 

Thanks @ahmelsayed for your help with the repro

**Comment by ahmelsayed** [comment] 2015-07-21 23:49
@galcho we can close this now, right?

**Comment by dgilling** [comment] 2015-09-20 23:23
When is this deployed I too see my project setting wiped out. I have multiple sites in the same repo (API, website, admin, etc). 
When I don't use staging slots, Project setting seems fine. 
Once I use deployment slots, the Project setting is wiped out as soon as I swap or restart the instance. All the other settings are persistent.

**Comment by davidebbo** [comment] 2015-09-21 03:52
@dgilling quite strange that it would only affect that setting. Do you have it set as a 'slot setting', or regular? And do you see this consistently? i.e. if you

- set PROJECT in the Azure App Settings
- restart the site

Then it consistently disappears, and you no longer see it in the portal?

**Comment by dgilling** [comment] 2015-09-25 19:03
I have tried having it set as a sticky "slot setting" both in production and staging and also as a non-slot setting. Doesn't seem to make a difference. All other settings stay put, it is only the Production key/value that seems to get wiped out. Using the classic Portal seemed to lower the probability of it happening, but it still happens and then I have to rush and re add it.

**Comment by davidebbo** [comment] 2015-09-25 19:08
And to be clear, you are seeing the wipe out as a simple result of restarting your site, even without involving any swaps? To investigate this, we would need from you:

- your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
- the UTC time at which you observe a restart causing your PROJECT app setting to disappear (which specify which slot that happened in)

**Comment by dgilling** [comment] 2015-09-25 19:32
Sorry, it's intermittent. I tried just now but it was persistent. Maybe a god thing.
If I see it in the next day or so, I will ping again.

It did happen about an hour ago, but I didn't note the timestamp nor which site.

**Comment by dgilling** [comment] 2015-10-01 23:42
It just occurred today around 4:30 PM PST:

My site is:
usetrove-api-production-south-central-us.azurewebsites.net

Both the Production and the staging slot "Project" Settings were wiped out. All other key/value settings remained persistent.

**Comment by davidebbo** [comment] 2015-10-01 23:45
And you are seeing the wipe out as a simple result of restarting your site, even without involving any swaps?

**Comment by dgilling** [comment] 2015-10-01 23:48
Yes

**Comment by davidebbo** [comment] 2015-10-01 23:50
Ok, I need to very clear about what action you took around that time. So you didn't do a swap at all. Did you restart both the production site and the staging slot? And then you noticed the PROJECT setting was gone in both? I can look at our logs and see what operations happened.

**Comment by dgilling** [comment] 2015-10-01 23:54
So for my first comment, I did a swap, that was around 4:30 PM PST.
After the swap, I noticed the Project setting was gone in both staging and production.
I then re-added and confirmed that the settings were added.

After you asked if is wiped out on only a restart, I performed a restart on staging slot via Azure Portal.
After restart, I again checked and it was wiped out again.

**Comment by davidebbo** [comment] 2015-10-02 00:15
Here is what I see in our logs, in term of API calls to that site and slot:

- 16:28:25: swap
- 16:39:28: change config Prod
- 16:39:48: change config Staging
- 16:47:21: restart staging
- 16:47:52: restart staging

Interestingly, I don't see a call to save the settings after that, yet I can see that the staging slot does have the PROJECT setting right now.

**Comment by dgilling** [comment] 2015-10-02 00:20
hmm. Just did a restart again at 5:19 PM PST.
Seemed to get wiped out. Didn't add and save after restart yet.

**Comment by davidebbo** [comment] 2015-10-02 00:22
Can you chat on https://jabbr.net/#/rooms/kudu? It will be easier :)

**Comment by dgilling** [comment] 2015-10-02 00:34
There

**Comment by davidebbo** [comment] 2015-10-02 00:34
A couple things you can try when that happens:

- Go to https://usetrove-api-production-south-central-us-staging.scm.azurewebsites.net/Env. Does PROJECT show up in there?
- Go to https://resources.azure.com/ and navigate to the site, then the slot, and then config/appsettings under that. Is PROJECT there?

**Comment by davidebbo** [comment] 2015-10-02 01:40
Status: after chatting with @dgilling, can are now able to repro the issue as well. We still don't have a full understanding of it, but it is a good step forward.

**Comment by davidebbo** [comment] 2015-10-05 19:21
Re-opening since the issue still exists. It is now understood and a fix is in the work. No clear ETA yet.

**Comment by chrisfoster78** [comment] 2017-02-01 14:04
We have a deployment slot that loses it's settings each time it is restarted.  Oddly it's SCM_BUILD_ARGS and PROJECT that disappear but not our custom setting of "ServerRole".

**Comment by chrisfoster78** [comment] 2017-02-01 14:28
I've just tried on another website slot and the same thing is happening. It does not appear to happen when restarting the parent website i.e. only slots.  I'm a little surprised that we've not noticed it earlier given that the bug appears to be widely spread and in existence so long.

**Comment by davidebbo** [comment] 2017-02-01 15:21
@chrisfoster78 We will look into this.

**Comment by davidebbo** [comment] 2017-02-01 15:40
I confirm that there is an issue. It's likely different from the original one, which was long fixed (we just forgot to close). Instead, it's probably a more recent regression.

**Comment by davidebbo** [comment] 2017-02-01 18:52
@chrisfoster78 I talked to the expert, and he gave me a workaround. It's going to sound strange, but I tried and it does work.

1. Make sure the required app settings are present on the slot
2. In Portal, click Swap, and choose _swap with preview_ as the swap type. Press Ok. This will do the first half of the _swap with preview_.
3. Instead of completing the swap, choose to cancel it (so you're not actually swapping anything)

At this point, whatever values you had before those steps are what you'll end up with after you restart the site.

In addition, he will fix the issue for a future deployment, but for now this should get you going.

**Comment by chrisfoster78** [comment] 2017-02-02 20:55
@davidebbo Thanks for the quick update. I'll let the team know to give it a whirl next time we need to restart.

**Comment by davidebbo** [comment] 2017-02-02 20:56
Cool. And to be clear, they'll only need to do this once, not every time they need to restart (unless the values of those settings need to change).

**Comment by davidtwamley** [comment] 2017-03-14 19:09
I frequently lose SCM_BUILD_ARGS on multiple sites. I've improved the situation by catching this issue as early as possible in the build process by adding this to my csproj:

**Comment by jvano** [comment] 2024-04-29 11:20
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Closed by jvano** 2024-04-29 11:20 UTC
