### ISSUE TITLE
Deployment logging slows the build tremendously

### ISSUE THREAD

**Issue by sebastienros** [projectkudu/kudu#1622] opened 2015-07-17 22:05 UTC
My project contains thousands of files to output (guess which project it is). The task output all these files in the console, and Kudu creates a new entry tag in its deployment log file for every new line.

```xml
        <entry time="2015-07-17T20:24:11.304537Z" id="1a9c5937-9e92-4135-a3bd-94dcaf2d959d" type="0">
            <message>  Copying file from "D:\home\site\repository\build\Compile\System.Web.WebPages.Razor.dll" to "D:\home\site\repository\build\Compile\_PublishedWebsites\Lucene\bin\System.Web.WebPages.Razor.dll".</message>
        </entry>
        <entry time="2015-07-17T20:24:11.5470539Z" id="7aabecc1-5270-4945-be6c-459f6bb85107" type="0">
            <message>  Copying file from "D:\home\site\repository\build\Compile\System.Web.Razor.dll" to "D:\home\site\repository\build\Compile\_PublishedWebsites\Lucene\bin\System.Web.Razor.dll".</message>
        </entry>
        <entry time="2015-07-17T20:24:11.8595585Z" id="9f135636-24b9-44e7-814a-af5872fd03a6" type="0">
            <message>  Copying file from "D:\home\site\repository\build\Compile\Owin.dll" to "D:\home\site\repository\build\Compile\_PublishedWebsites\Lucene\bin\Owin.dll".</message>
        </entry>
```

This makes the build process much slower than usual, in my case around 1h30, because I assume the file is flushed on the disk every seconds or so, and when the file reaches 1MB then most of the time is spent writing on disk.

I would suggest having an option to use a simple append only text file at least as the XML structure makes it very slow in this case.

**Comment by davidebbo** [comment] 2015-07-18 03:04
May be interesting to try with a private build of Kudu that skip these logs to make sure that's the cause.

Can you give more details about your scenarios? e.g.

- link to the exact repo you're deploying
- how are you deploying? e.g. direct git push vs GitHub, ...

**Comment by sebastienros** [comment] 2015-07-19 16:53
Take orchard on branch 1.9.x. Which has Kudu support OOB now by disabling the log. Deploy using Kudu, it will take 20mins top. Now edit deploy.cmd and remove the /v:m to remove the minimal logging level. Redeploy, it will take more than 1 hour. Another way to see the difference is to run depoy.cmd in the console, which doesn't get logged in the xml, and is much faster with the same amount of output strings.

Deployment was done using github commits.

**Comment by davidebbo** [comment] 2015-07-23 01:26
Yes, the current  xml is horribly inefficient once it gets large. We had the same issue for the trace file (#419), which we fixed by using individual files per entry. But here it's a bit trickier because entries are hierarchical. Also, unlike trace, which is non-essential, we'd need to support both old and new formats.

There may be a less disruptive approach that keeps the format mostly the same, but doesn't generate a separate entry for each line. i.e. everything under 'Running deployment command...' could just be one big string.

**Comment by davidebbo** [comment] 2015-08-04 20:41
@sebastienros I tried deploying https://github.com/OrchardCMS/Orchard branch 1.9.x, but that failed early (*error MSB4057: The target "PreComputeCompileTypeScript" does not exist in the project.*). What is the right way to test your scenario?

**Closed** 2015-08-05 19:20 UTC

**Comment by davidebbo** [comment] 2015-08-27 00:32
@sebastienros, this change is now live. Can you please test the same scenario that you had tried before to see how much that improves things?
