### ISSUE TITLE
Read web.config XML in Azure Web Jobs

### ISSUE THREAD

**Issue by ricardopolo** [projectkudu/kudu#1571] opened 2015-05-28 16:52 UTC
You have a web job with some settings that you read using ConfigurationManager.AppSettings.

ConfigurationManager.AppSettings reads parameters configure through the Azure Portal. Is it possible to read the ones configured in the web.config of the website instead the the settings configure in the Azure Portal?

If not, why not? Is a WEB job so sould use WEB site settings...
Would you accept a PR doing this?

**Comment by davidebbo** [comment] 2015-05-28 17:48
@amitapl is the expert, but I think the code that relates most to this is [here](https://github.com/projectkudu/kudu/blob/285ff6ca1400156f86a5be1a9381b2e02619dfcf/Kudu.Core/Jobs/BaseJobRunner.cs#L381-L425).

What it does today is basically copy things from the Azure AppSettings/ConnStrings, into the `.config` file for the WebJobs.

In order to do what you ask for, the code would need to:
- find the sites's web.config
- read the settings from it. Presumably, that can be done using `ConfigurationManager.OpenExeConfiguration`, the same way we're writing to the WebJobs config
- copy those settings to the WebJobs config

It needs to be done carefully, because the Azure config settings are supposed to override the web.config settings. So if you have a `foo` setting in both, you need to make sure that the Azure setting wins for the WebJob.

**Comment by amitapl** [comment] 2015-05-29 17:12
Personally I think it is the wrong behavior to read the web.config for the WebJob.
This is since they are 2 disconnected processes running on the same environment and the shared part should be in the environment.

That said, if enough customers say this is a feature they want/need we should do it.
Still it would require some specific configuration otherwise we could break existing WebJobs that did not expect this behavior.

**Comment by ricardopolo** [comment] 2015-05-29 19:31
So @amitapl any idea how you can configure the WebJob settings using a CI Server?

I know I can find a string in the app.config and replace it, but I think this is too manual.

In the Website you can create a parameters.xml file and the Web Publishing Process use it 
https://msdn.microsoft.com/en-us/library/ff398068%28v=vs.110%29.aspx

But there is such a thing for web jobs?

**Comment by davidebbo** [comment] 2015-05-29 20:30
I chatted with Amit. The risk of breaking existing WebJobs is minimal, so it's not a concern. We just need to make sure that we use the right order of precedence: Azure Setting falls back to WebJobs config falls back to site' web.config.

So all in all, I do think it's a valid change to make!

**Comment by amitapl** [comment] 2015-05-29 20:58
For now as a workaround you can include your app settings from an external file like this:
`<appSettings file="externalSettings.config"/>`

**Comment by tbaggett** [comment] 2015-08-11 22:24
@amitapl, adding the file attribute doesn't appear to work, or at least it didn't for me. I added the following to my WebJob project's App.config file:

'<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings file="PrivateSettings.config">
    <add key="test" value="test again"/>
  </appSettings>
  <startup> 
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
...'

I then started a debug instance of the WebJob and set a breakpoint after executing the following line in the Program.cs file's Main() method:

'var settings = ConfigurationManager.AppSettings;'

When inspecting the "settings" var, I only see the single "test" entry. There are approximately 20 additional entries in the "PrivateSettings.config" file, but they don't show up in the settings variable.

I've included the same PrivateSettings.config file in my ASP.NET MVC WebApp project and it works without issue there.

**Comment by davidebbo** [comment] 2015-08-11 22:44
@tbaggett does it work if you run the WebJobs exe locally? What about if you run it manually on Azure using [Kudu Console](https://github.com/projectkudu/kudu/wiki/Kudu-console)? ANd make sure from Kudu console that all files were correctly deployed with the WebJobs. If your PrivateSettings.config is missing, it won't work.

**Comment by tbaggett** [comment] 2015-08-11 22:47
Hi @davidebbo, I have only tested it by running locally so far. It didn't work there as I described. 

I will try deploying it and report back on what I see.

**Comment by davidebbo** [comment] 2015-08-11 22:48
I see. I wouldn't bother trying to deploy it till you can get it working locally. But it should work, as it's a standard .NET feature that's been there for 10+ years.

**Comment by tbaggett** [comment] 2015-08-11 22:53
I hear ya, @davidebbo. Like I mentioned, the "file" attribute is working fine elsewhere in the project with the same PrivateSettings.config file, but not in my WebJob project. 

That file is normally stored outside of my project files, so I have to reference it like "..\..\..\..\..\PrivateSettings.config". I thought that in this case, the number of "..\" entries were off, so I copied the file to the WebJob project folder and tried it again. Still no dice, only the explicitly defined "test" entry in the App.config file is showing up. I also tried adding the PrivateSettings.config file to the WebJob project but that didn't make any difference either.

**Comment by davidebbo** [comment] 2015-08-11 22:59
I just tried it in a trivial console app, and it works fine. Can you try https://github.com/davidebbo-test/ConsoleApplicationExternalAppSettings and confirm that it works for you? The trick was to set Copy to Output Directory for the external file.

Note that if it can't find the file, it simply ignores it and does not fail. That's how this feature works. Anyway, at this point that is not Kudu related.

**Comment by tbaggett** [comment] 2015-08-11 23:48
Thanks for taking the time to try that, @davidebbo, much appreciated. You're correct, setting the Copy to Output Directory made it work. However, that requirement here leaves me wondering how it has been working in my WebApp project. I just confirmed again that is working without issue there. 

In that case, the config file being referenced is completely outside of the project's directory structure. It isn't included or referenced anywhere in the project except for the file= attribute in the Web.config file. Apparently there is something different in the handling based on it being in App.config or Web.config, console app vs. DLL.

Thanks again and sorry for the unrelated noise!

**Comment by davidebbo** [comment] 2015-08-12 00:22
It's not console ap vs DLL, but more console app vs web app. In Console app, there are more funky things happening. What you write as app.config actually becomes `ConsoleApplicationExternalAppSettings.exe.config` (or whatever your exe name is), and goes in a different folder, e.g. in bin\debug. But with web apps, web.config works as is, so less magic.

**Comment by tbaggett** [comment] 2015-08-12 00:37
Thanks for those details; that makes sense. 

Fortunately, being armed with the knowledge you provided, I made it work as desired. I deleted the local copy of the settings file from the WebJob project, but left the App.config's "appSettings file=" reference untouched (still just file="PrivateSettings.config"). Next, I chose "Add - Existing Item - Add as Link" to add a reference to the settings file from outside of my project structure to the WebJob project. VS now shows the file as a shortcut in the Solution Explorer, and the file continues to be copied to the output folder when I build. 

Onward forward, as they say. Thanks again for your help.

**Comment by ricardopolo** [comment] 2015-08-12 01:55
I have a question about this method (the workarround) of add a file as link.

If you modified your web.config on the CI server when creating the WAP packages (Publishing) using the parameters.xml file (https://msdn.microsoft.com/en-us/library/ff398068(v=vs.110).aspx). It still works?

**Comment by davidebbo** [comment] 2015-08-12 23:28
The `<appSettings file="PrivateSettings.config">` syntax will work regardless of how you deployed the site, being FTP, WebDeploy, git, ... In the end, what matters is what files are deployed, and not how they got deployed.

**Comment by ricardopolo** [comment] 2015-08-13 00:59
I am talking about the app.config modifications using parameters.xml file

**Comment by jsgoupil** [comment] 2015-12-30 23:32
I am having some issues with this here where when I use the  `<appSettings file="AppSettings.config" />` , it actually overrides everything that is set in the Azure Portal.

By reading this post here, it seems that I want the opposite of what the guy who opened the bug wants?

My goal was to avoid having AppSettings duplicated across all my projects, so I created a AppSettings.config file set to "Copy if Newer" added as a link.
I did the same thing with connection strings `<connectionStrings configSource="Connections.config" />`

However, when accessing ConfigurationManager.AppSettings, none from the Azure portal overrides my AppSettings.config file. On the other hand, the Connections.config is being overwritten successfully.

Am I missing something here?

**Comment by davidebbo** [comment] 2015-12-30 23:52
@jsgoupil yes, I think understand why it does this, though I would not call it deliberate. The whole `file="AppSettings.config"` was a workaround for someone who didn't want to use Azure App Settings at all, and they don't play so well together (in the WebJobs case).

Is your goal to override all the settings from `AppSettings.config` using Azure App Settings, or only a subset of them?

**Comment by jsgoupil** [comment] 2015-12-30 23:54
@davidebbo Thanks for the fast reply. My goal was to behave like Azure Website. That way I get no surprises.

Basically Azure Portal overrides the settings that are found or create new settings if they are not found. If the Azure Portal does not have some settings from the appSettings, then they are simply working but not overridden

Basically I was expecting to get the exact same thing as:

https://<website>.scm.azurewebsites.net/api/settings.

**Comment by davidebbo** [comment] 2015-12-31 00:01
Yes, it ideally would work like that. Some background:

For Web Apps, it works by injecting the settings into the config system at **runtime** (using logic like [this](https://gist.github.com/davidebbo/2b961ad298683987547c)), overriding and 'normal' .NET settings (whether the come from regular config or external file). i.e. the physical config file is never modified.

But for WebJobs, which are Console apps, there is no easy way to inject those things at **runtime**. So instead, before we run the WebJob, we have logic that physically modifies the WebJob's config file to set the settings from Azure, overriding what was in there. The problem is that this logic is not aware of external `file="AppSettings.config"`, and that external file ends up 'winning' over what we replaced.

Hopefully that made sense :) And I know it doesn't help solve it, but at least it should clarify why things work the way they do...

**Comment by jsgoupil** [comment] 2015-12-31 00:05
@davidebbo It surprised me because the connection string works the right way, probably because the connectionString functionality thought of this scenario.
I understand how the fix would be, probably to read the file="*" then create this thing in memory from the settings you found and the one from Azure.
Interestingly, I checked also on the FTP in the App_Data/jobs and the *.exe.config does not contain the latest from the portal. Do you revert back once the app started?

Anyway, do you think we could track this as a different bug then? If someone fancy to fix it some day ;)

**Comment by davidebbo** [comment] 2015-12-31 00:13
I'm not sure why the same doesn't happen for connection strings.

The reason you don't see the change in the file is that we don't run it in place, but shadow copy it to a temp location (to avoid locking). The copied config file has the changes.

Sure, feel free to open a separate issue to track. e.g. "Azure App Settings don't override external config files in WebJobs". And we'll take a PR if you have the cycles :)

**Comment by ichivers** [comment] 2016-02-01 16:24
This works if you need to get to the parent web app's web.config:

```
string webConfig = Environment.GetEnvironmentVariable("WEBROOT_PATH") + @"\web.config";
            ExeConfigurationFileMap configMap = new ExeConfigurationFileMap { ExeConfigFilename = webConfig };
            Configuration config = ConfigurationManager.OpenMappedExeConfiguration(configMap, ConfigurationUserLevel.None);
            Console.WriteLine("testprod=" + config.AppSettings.Settings["testprod"].Value);
```

**Comment by davidebbo** [comment] 2016-02-01 17:16
@ichivers thanks for sharing!

**Comment by Bartolomeus-649** [comment] 2017-01-26 14:00
You really need full access to the configuration file. There are setting all over you might need. For example settings for email is in System.Net, Connection strings has its own section,. Then you have applicationSettings in its own section (not to be confused with appSettings), and then we have any number of custom sections that the app might ave created.
And you can't just move settings out to an external file and reference it, it will break a lot of functionality in Visual Studio.

And i don't believe in moving/syncing them to any other config file.  The best approach would be to provide some kind of API to read the main config file of the website.

**Comment by profectusit** [comment] 2018-02-05 12:56
Hi @davidebbo, 

I think I have a similar problem.

I have an azure webjob and I would like to separate the system.diagnostics part out of the app.config into the diagnostics.config file and make just a “configSource”-reference in the app.config. This works locally as ConsoleApplication and also in other projects as WebApplications. But as soon I publish my ConsoleApplication as a WebJob it breaks during the start of the WebJob with the exception message: "Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: A section using 'configSource' may contain no other attributes or elements."
If I copy the system.diagnostics stuff in the App.config it works fine.
The same syntax works with the connectionString.config!
I have tested it in different Jobs overall with the same behavior! It works locally and in WebApps, but not in WebJob. BTW: the diagnostics.config exits in the right folder.
I guess there is something missing in your merge-and-deployment-process...

It would be great if you have a solution for me.

Here is a snippet of the config:
	
	<system.diagnostics configSource="diagnostics.config"/>

**Comment by davidebbo** [comment] 2018-02-05 18:23
@profectusit that is probably not related to this issue. Kudu does special handling for App Settings and Connection Strings, but nothing at all for system.diagnostics.

**Comment by profectusit** [comment] 2018-02-06 11:05
@davidebbo Thanks for your answer. I thought that Kudu runs in every scenario if I will deploy and run a webjob and therefore all app.config-migrations will go trough Kudu!?

**Comment by davidebbo** [comment] 2018-02-06 20:42
@profectusit is always involved to run WebJobs, but it only has special handling for those two specific things. If it doesn't work, it may be missing your file. Please start a separate issue so we don't intermix the two.

**Comment by jasonds** [comment] 2018-04-05 15:51
@profectusit / @davidebbo - was a separate thread started or did you find the answer here? I am experiencing the exact same issue. I checked in the temp instance of the WebJob located here:
D:\local\Temp\jobs\continuous\{jobName}\{jobInstanceId}

I confirmed that three trace listeners have been added automatically, which causes this issue:

`  <system.diagnostics configSource="Diagnostics.config">
    <trace>
      <listeners>
        <add name="AzureBlobTraceListener" type="Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener, Microsoft.WindowsAzure.WebSites.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
        <add name="AzureTableTraceListener" type="Microsoft.WindowsAzure.WebSites.Diagnostics.AzureTableTraceListener, Microsoft.WindowsAzure.WebSites.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
        <add name="AzureDriveTraceListener" type="Microsoft.WindowsAzure.WebSites.Diagnostics.AzureDriveTraceListener, Microsoft.WindowsAzure.WebSites.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
      </listeners>
    </trace>
  </system.diagnostics>`

**Comment by davidebbo** [comment] 2018-04-05 16:04
@jasonds this issue is not related to trace listeners, and I think it has slowly migrated from its original question to something quite different. I will close this one to avoid further confusion. Please open a separate issue and please give more details about what you are running into with trace listeners causing problems.

**Closed by davidebbo** 2018-04-05 16:04 UTC
