### ISSUE TITLE
Build fails with one custom package source

### ISSUE THREAD

**Issue by jfoshee** [projectkudu/kudu#1657] opened 2015-08-13 03:42 UTC
## Symptom

A solution that has a `nuget.config` with one custom key under `<packagesources>` will fail to deploy. Upon inspecting the **Deployment Details** > **Activity Logs** the user will discover output like the following:

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
Unable to find version '5.6.4' of package 'Microsoft.Data.Edm'.
Failed exitCode=1, command=nuget restore "D:\home\site\repository\UrlShortening.sln"
Unable to find version '5.6.4' of package 'Microsoft.Data.OData'.
An error has occurred during web site deployment.
Unable to find version '5.6.4' of package 'Microsoft.Data.Services.Client'.
Unable to find version '3.1.0' of package 'Microsoft.WindowsAzure.ConfigurationManager'.
Unable to find version '7.0.1' of package 'Newtonsoft.Json'.
...
```

The build passes locally in Visual Studio (probably because the NuGet package source is added to the environment by default) as well as on AppVeyor.

**Repro:** https://github.com/Durwella/UrlShortening/tree/0f85db19f033995f325b14cf9f6fb758961c39f9
## Root Cause

The package(s) located at the custom package source will be found. However packages located at the "default" NuGet package source will not be found. 
## Mitigation

Add the NuGet package source to the nuget.config

```
<packageSources>
    <add key="NuGet official package source" value="https://nuget.org/api/v2/" />
    <add key="My custom source" value="http://example.packagesources" />
</packageSources>
```
## Suggestion

It's not obvious that this should be "fixed". But, given that the build works in other places it is confusing.  Either one of the following two options would be helpful in this case:
1. After a build fails, if it fails due to missing packages _and_ their exists a nuget.config with `<packageSources>` _and_ the nuget.org value is missing, then print a warning message to the log such as 
   
   > Your build failed due to missing packages. If you use standard packages then consider adding the following to the `<packageSources>` section of your nuget.config: `<add key="NuGet official package source" value="https://nuget.org/api/v2/" />`
2. Include a `nuget.config` in a parent directory that includes the standard NuGet package source. It seems that it will be [chained together](https://docs.nuget.org/consume/nuget-config-file#chaining-multiple-configuration-files) with the solution-level nuget.config.  
   It could be that some users actually want to exclude the nuget.org package source. They could still achieve this using  `<clear />` as the first line inside of `<packageSources>`. I'd expect this to be the less-than-20% case.

_Thanks!_

**Comment by davidebbo** [comment] 2015-08-14 00:36
@jfoshee thanks for reporting. As you suggest, the reason it works on VS machines is that VS installs a `%APPDATA%\nuget\NuGet.Config` which has the default package source. And it might be that AppVeyor build machines also have VS. But if you run the same nuget.exe command on some random machine, I think you'd see the same error. In that sense, I'm leaning toward thinking it is not a bug, but is the NuGet.exe design.

As for improving the error reporting, I think it's something that should live in NuGet.exe. All we do in the Azure build is run NuGet.exe, and we have zero knowledge of nuget.config. As such, it would feel dirty having to look for it (I think it can be anywhere in the parent folder chain), parsing and and making error handling decision based on what it contains.

**Comment by willthiswork89** [comment] 2017-09-27 03:30
I'm having this problem right now... The mitigation does not work however. I have to remove the custom package source... let the microsoft packages install and let the build fail then add back my custom package location and rebuild and it will then use the cached versions it downloaded already of microsoft packages and then find mine...  something is definitely not right with this.

**Comment by willthiswork89** [comment] 2017-10-02 18:09
https://stackoverflow.com/questions/46531036/nuget-package-restore-fails-for-webapp-with-custom-nuget-config

**Comment by davidebbo** [comment] 2017-10-02 19:06
@willthiswork89 having you reproed this from straight Kudu console, to isolate from any other part of Kudu deployment? Is that with nuget restore, or dotnet restore?

**Comment by willthiswork89** [comment] 2017-10-02 19:16
Hi David I am not positive it's whatever runs for a webapp and .netcore . I am not super familiar with kudu but can try this tonight

**Comment by davidebbo** [comment] 2017-10-02 19:29
@willthiswork89 yes, please do isolate down to a minimal repro, per [wiki](https://github.com/projectkudu/kudu/wiki/Isolating-WebJobs-and-Deployment-script-issues).

**Comment by willthiswork89** [comment] 2017-10-03 20:43
The problem occurs inside the kudu console as well with a dotnet restore

**Comment by davidebbo** [comment] 2017-10-04 01:20
I'm not sure what's going on. In the end, this is using the standard 'dotnet restore', so it should work the same on Azure as anywhere else. Maybe it is not finding your customer feed. Are you using nuget.config to specify it? And are you sure that the same works on a machine that doesn't the feed registered machine level?

**Comment by willthiswork89** [comment] 2017-10-04 12:47
So The workaround i have found is to remove my nuget config, do a dotnet restore. It will pull all microsoft packages into cache then fail to find my custom packages. From there i reinstall my nuget.config with my custom source, and run the dot net restore again.... this will then use the microsoft packages from cache and then pull the custom packages down just fine from my custom source and the build will succeed. 

It seems to be something with multiple package locations causing it. The nuget.config i used to do this was copied from my development machines %appdata%\nuget\nuget.config

**Comment by willthiswork89** [comment] 2017-10-04 12:48
And yes the custom package URL works fine on a dev machine

**Comment by willthiswork89** [comment] 2017-10-04 16:14
`
<?xml version="1.0" encoding="utf-8"?>

<configuration>

  <packageSources>

    <add key="NuGet official package source" value="http://nuget.org/api/v2/" />

    <add key="OTL" value="http://www.myget.org/F/**{Redacted}/**api/v3/index.json" />

  </packageSources>

  <packageRestore>

    <add key="enabled" value="True" />

    <add key="automatic" value="True" />

  </packageRestore>

  <bindingRedirects>

    <add key="skip" value="False" />

  </bindingRedirects>

  <packageManagement>

    <add key="format" value="0" />

    <add key="disabled" value="False" />

  </packageManagement>

  <disabledPackageSources />

</configuration>`

**Comment by willthiswork89** [comment] 2017-10-04 16:15
I have tried http, https, nuget.org/v3 of the api tons of things... The only way I get it to work is to remove the config, let kudu get the packages from nuget, then fail to find custom packages. Then add my nuget.config back with the custom package location and kick the deployment off again

**Comment by davidebbo** [comment] 2017-10-04 16:19
If you can share a small [repro repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) of this, I'll investigate what might be going on. You can set up a dummy myget feed if you don't want to show your real one.

**Comment by willthiswork89** [comment] 2017-10-05 17:02
Great ill get one put together tonight after work for you. Appreciate any help and insights.

**Comment by willthiswork89** [comment] 2017-10-11 14:36
Hey @davidebbo finally got this replicated sorry it took so long. I trimmed out as much as possible to still have a functioning build. Its public at https://github.com/willthiswork89/testnugetfailure

**Comment by willthiswork89** [comment] 2017-10-11 14:42
So to replicate, just attempt to deploy that app into a WebApp on Azure and kudu will kick off and fail because of a strange error about failing to connect to pull down microsoft nuget packages. 

Once that happens, delete the nuget config and run it again. It will fail again but this time it will succeed with getting nuget references for microsoft, then fail getting them for the custom packages. 

Once that happens, add the nuget config BACK untouched. Now it will restore the microsoft packages from the local location and then use the custom location and pull down my custom packages fine and the build will succeed and deploy.

**Comment by davidebbo** [comment] 2017-10-11 16:05
@willthiswork89 perfect, I'll take a look, thanks!

**Comment by davidebbo** [comment] 2017-10-11 16:52
Ok, I can indeed repro this, and I'm going to need help from NuGet experts to figure out what's causing it.

@emgarten maybe you can help?

Situation is:

- We run within the App Service sandbox
- We set `DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true`
- `nuget.config` points to both nuget.org and another source (see it [here](https://github.com/willthiswork89/testnugetfailure/blob/master/NuGet.config))
- We run `dotnet restore` within the App Service sandbox

And for some reason, it fails to restore nuget package, with error above. But if nuget.config just has nuget.org, then it works fine.

**Why would the second feed break restore?**

**Comment by willthiswork89** [comment] 2017-10-11 18:33
I'm glad you were able to repro. Whats more interesting is the fact that if you take JUST nugget config, restore then swap it for the custom, they both work individually but not together

**Comment by emgarten** [comment] 2017-10-12 00:27
I haven't seen an additional feed cause problems like that. The error message around missing packages has been improved in NuGet 4.3.0/dotnet CLI 2.0.2, is there any chance you could restore using that?

In the latest version it will tell you which feeds it tried, and what package versions were found.

**Comment by davidebbo** [comment] 2017-10-12 01:19
@emgarten are you sure that has been released? The latest I see on https://www.microsoft.com/net/download/core#/sdk is 2.0. How would one get 2.0.2?

**Comment by davidebbo** [comment] 2017-10-13 00:23
Ok, so I figured out the root of the mystery. The App Service sandbox limits the socket connections to 300, and it seems that having two feeds causes NuGet to blow that limit, while having just one stays under the limit. That explains the puzzling behavior.

Now we need to figure out how to make NuGet less socket greedy...

**Comment by davidebbo** [comment] 2017-10-13 00:23
One more thing...

@willthiswork89 what App Service Plan were you using? I believe the 300 limit only exists in Free/Shared. So in theory this should not happen in Basic/Standard.

**Comment by willthiswork89** [comment] 2017-10-13 00:43
Aha! This makes sense. We are indeed running on the free version. So no work around for now then other than upgrading to basic tier then downgrading.

**Comment by davidebbo** [comment] 2017-10-13 00:47
Right, unless NuGet has some secret mechanism for reducing concurrency.

**Comment by davidebbo** [comment] 2017-10-13 00:49
Oh, @emgarten just told me that you can run `dotnet restore --disable-parallel` which limits things to a single http connection. So give that a try! You'll need a custom deployment script to tweak how this is called.

Though it'll probably run a low slower.

Closing here since there is really nothing to be done in Kudu itself. See also https://github.com/NuGet/Home/issues/4538.

**Closed by davidebbo** 2017-10-13 00:49 UTC

**Comment by emgarten** [comment] 2017-10-13 00:51
You could also try setting the property `<RestoreDisableParallel>true</RestoreDisableParallel>` in all csproj files (or including a props file that does this to workaround this if you aren't calling dotnet restore yourself.

The command line sets this property in MSBuild and is picked up restore, setting it in your projects would have a similar effect.

**Comment by davidebbo** [comment] 2017-10-13 00:52
@emgarten nice! That'll avoid the need for a custom deployment script. On the downside, that'll make the restore slow on your local machine.
