### ISSUE TITLE
Could not resolve hostname

### ISSUE THREAD

**Issue by knives81** [projectkudu/kudu#2246] opened 2016-12-01 18:11 UTC
I followed this procedure to configure my Github Enterprise but I got this error
https://nsamteladze.wordpress.com/2015/07/19/continuous-deployment-from-github-enterprise-repository-to-azure-web-app/

**ssh: Could not resolve hostname github.<mycompany>.com: Name or service not known\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\r\nD:\Program Files (x86)\Git\cmd\git.exe fetch origin --progress**

any help

**Comment by davidebbo** [comment] 2016-12-01 18:22
The two periods in `github..com` look kind of suspicious :)

**Comment by knives81** [comment] 2016-12-01 18:28
Part of the comment has been removed It was github.mycompany.com

**Comment by davidebbo** [comment] 2016-12-01 18:51
I see. I'd start start by trying things manually from Kudu Console. This way you keep any Kudu deployment logic completely out of the equation.

**Comment by knives81** [comment] 2016-12-02 13:21
It looks like Github Enterprise must be accessible from internet which is not the case for us

**Comment by davidebbo** [comment] 2016-12-02 15:54
Yes, of course, this will not work if Azure cannot access the repo. Closing since this is basically by design.

**Closed by davidebbo** 2016-12-02 15:54 UTC
