### ISSUE TITLE
Add optional support to restore nuget packages recursively

### ISSUE THREAD

**Issue by marknuzz** [projectkudu/kudu#1974] opened 2016-04-23 00:27 UTC
Nuget packages in submodules are not restored before build. 
I found a powershell line here, that when executed instead of "nuget package restore", properly restores the packages.  Using the standard nuget restore simply says "all packages already installed" and then the build obviously fails after that.
https://gist.github.com/jongalloway/cc6cb3885fe1777a05ac

`get-childitem . -include *.sln -recurse | foreach ($_) { nuget restore $_.FullName -verbosity detailed}`

**Comment by mnuzzolilo** [comment] 2016-04-23 01:35
A workaround is to set project hint paths in the submodule csproj file to use $(SolutionDir)\packages\foo\bar instead of packages\foo\bar. But this is not an option for everyone. Unless there is a specific downside to recursing the package restore command, I would think it's a more flexible option with less user headache.

**Comment by davidebbo** [comment] 2016-05-04 00:00
Generally, the process that does the build knows nothing about submodules. It looks at all the files in the repository folder, regardless of whether they all came from one repo or multiple.

Submodule aside, if the default deployment script doesn't do what you want, you can switch to using a [custom deployment script](http://blog.amitapple.com/post/38417491924/azurewebsitecustomdeploymentpart1), which lets you run nuget in any way you want.

**Comment by mnuzzolilo** [comment] 2016-05-04 00:14
Thanks for the reply.  Kudu is using git in its deploy script is it not? Is it correct design to support git projects in the standard deploy script, but completely fail with those projects that employ the standard submodule pattern that many projects use?  

I obviously can't force you to change your mind, but I think that your stance on this is a mistake which will ultimately hurt the quality of the product.  Is there any way this can be solved without expecting people to write their own custom scripts?

**Comment by davidebbo** [comment] 2016-05-04 00:56
No, the deploy script is actually agnostic of git. The general high level flow is:

- Do the git update (including submodules)
- Run the deployment script, which works with whatever files end up in the repository folder (with git and submodules of no relevance at this point)

So I'm not sure what the issue is, but I'm fairly confident that it is not directly related to submodules. To see that, try creating a single repo containing the union of all your submodules. You'll likely see the same behavior.

**Comment by mnuzzolilo** [comment] 2016-05-04 02:13
Here is what the issue is: 


1. Kudu calls `git.exe submodule update --init --recursive` and then submodules are updated. 
At this point, the folder structure looks like:

```
mainsolution.sln
MainProject/MainProject.csproj
Submodule/Submodule.sln
Submodule/Submodule.csproj
```

2. The deploy script is run, which calls nuget package restore on mainsolution.sln via the below command

:: 1. Restore NuGet packages
IF /I "mainsolution.sln" NEQ "" (
  call :ExecuteCmd "%NUGET_EXE%" restore "%DEPLOYMENT_SOURCE%\mainsolution.sln"
  IF !ERRORLEVEL! NEQ 0 goto error
)

Right at this point when the NuGet packages are restored, the directory structure looks like this:

```
mainsolution.sln
packages/{all packages belonging to both main solution and submodule}
MainProject/MainProject.csproj
Submodule/Submodule.sln
Submodule/Submodule.csproj
```

The problem is that within submodule.csproj, *BY DEFAULT* references are relative to the csproj file and not the sln file.  At least this is true in the version of nuget I am using.  So compilation fails because ./Submodule/packages/whatever/whatever.dll is not found, but is instead placed in ./packages/whatever/whatever.dll.

The default deploy script doesn't know about git, but it could simply, for each .sln file which is not in the root directory, also execute the nuget package restore command for that respective folder.  An option to disable this behavior could be specified by the user so long as they are using the default deploy script. 

It's not exactly the simplest of fixes but I feel like this is something that should be fixed, even if you don't have the resources to do it outside of a community-submitted patch.

**Comment by mnuzzolilo** [comment] 2016-05-04 02:24
If this is something that is deemed too kludgey for default behavior then perhaps having it as an advanced option disabled by default would be okay too. Just thinking out loud

**Comment by davidebbo** [comment] 2016-05-04 02:30
First, we need to agree that the behavior you describe has nothing to do with submodules. You could have a regular plain repo that happens to have multiple solution files in various folders, and the same would apply.

I think the main danger with the recursive nuget approach is the possible perf issues. Some repos have 10000 folders with random stuff, and that directory walk could be slow.

The part I'm not clear about in your scenario: what specific project are you deploying? MainProject.csproj or Submodule.csproj? And are those two solutions in any way related, or are they each their own things?

Honestly, I don't think using a custom script is much of a burden for these more complex scenarios (I don't think this issue has come up before). You can very easily download the default scripts for your site (Tools menu in Kudu), modify a couple lines and get it in your repo. The default script only goes so far, and there are lots of reasons why people move to custom scripts. It's really a pretty simple thing that then gives you a ton more control over your deployment process.

**Comment by mnuzzolilo** [comment] 2016-05-04 03:06
To respond to the performance issues: There are a few options.  One of them is to have an option to specify recursive depth, with a default of one.  Or the behavior can be disabled.  Anyone who is the lead developer on a project with submodules, having a solution structure with that level of complexity, likely to understand how to use advanced options, but too busy to spare the time to build custom scripts just for this task.  As an accomplished architect, you may see batch scripts as a relatively simple thing.  But from my experience batch scripting is not as flexible of a tool as it was designed to be.  A lot of C# developers do not really do so well with batch scripting, myself included.  We can do it, but it is very time-consuming and headache-inducing.   

Even if I could write a batch script, a lot of team managers do not like having scripts that only one person can understand or maintain, because it is a liability to the project (believe it or not, a lot of small software companies hire younger devs that do not have this background).  Or they don't like having to pull Bob off of project A and have him fix project B every time something needs to be updated or diagnosed with the custom build script.  So is this fine for one-man projects?  I say that it still isn't, because one-man projects are supposed to be small and simple, and Kudu from my understanding is supposed to make things less painful and more simple.  Submodules are no longer a fringe use case and are becoming a standard thing. 

If the aforementioned edge case is not solvable with the options given, I imagine that another user will submit an issue here asking for help and then the issue can be dealt with as it arrives. Worst case scenario, they will have to have the behavior disabled and it will behave, for that user, as if we had done nothing here.  The standard, run of the mill use cases, will see that their nuget packages are no longer missing references.

I am deploying MainProject.sln. The two solutions, in my case, are related. And I even have my own workaround already done with.  But if Submodule.csproj were an open source project not under my control, my workaround would likely not work without a custom deploy script.


With that said, if you still think custom scripts are what is necessary, here is what I propose: The documentation should clearly explain the possibility of this issue occurring, and describe how to solve it by editing the build script (include the actual code). And explain the possible performance implications.

**Comment by mnuzzolilo** [comment] 2016-05-04 03:22
And yes to answer your question, I understand that this is not a problem unique to submodules, but submodules are the use case that virtually every instance of this problem will occur with in the real world.

**Comment by davidebbo** [comment] 2016-05-04 03:28
To be clear, I'm not against targeting this scenario if the community has the drive to make something happen and sends a PR. That's how a lot of things get done in the OS world :)

**Comment by mnuzzolilo** [comment] 2016-05-04 03:55
Thank you!  Could the issue be re-opened in that case? :+1:

**Comment by davidebbo** [comment] 2016-05-04 04:10
I changed the title to more precisely describe the need, and reactivated it.

**Comment by jvano** [comment] 2024-04-29 11:19
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Closed by jvano** 2024-04-29 11:19 UTC
