### ISSUE TITLE
Kudu can't deploy console app referencing netstandard packages

### ISSUE THREAD

**Issue by davidmatson** [projectkudu/kudu#2521] opened 2017-08-16 00:14 UTC
I'm unable to deploy a Console .NET Framework csproj (as a web job) if it contains a reference to a NuGet package that references netstandard2.0.

A repro repository is here:
https://github.com/davidmatson/kuduissue2521repro

Here's the error message I get:
```
remote: Program.cs(8,40): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\home\site\repository\ReferenceNetStandard20Library\ReferenceNetStandard20Library.csproj]
remote: Program.cs(8,27): error CS0012: The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\home\site\repository\ReferenceNetStandard20Library\ReferenceNetStandard20Library.csproj]
remote: Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\ReferenceNetStandard20Library\ReferenceNetStandard20Library.csproj" /nologo /verbosity:m /t:Build /p:Configuration=Release;OutputPath="D:\local\Temp\8d4e435d99c9bd6\app_data\jobs\continuous\deployedJob";UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\.\\"
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
```

Is Azure Web Apps currently running a preview version of .NET Core 2.0 tooling? I'm able to build locally when using VS 2017 Update 3 with the .NET Core 2.0 SDK (RTM versions of both).

**Comment by davidebbo** [comment] 2017-08-16 00:23
As of this morning, it's running the official ,NET 2.0 tooling if you use dotnet.exe to build. However, when using msbuild, it's possible that it's missing the latest bits.

Are you able to repro by simply building from Kudu Console? That makes a simpler repro that doesn't involve any git deployment.

**Comment by davidmatson** [comment] 2017-08-16 00:29
Thanks; the msbuild portion sounds likely to be the issue here.

I'm not sure this is the repro you're looking for, but I opened up a Kudu Console for this site (https://<myapp>.scm.azurewebsites.net/DebugConsole), changed to the repository directory, and ran msbuild. I get the same error.

```
"D:\home\site\repository\ReferenceNetStandard20Library\ReferenceNetStandard20Library.csproj" (default target) (2) ->
(CoreCompile target) -> 
  Program.cs(8,40): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\home\site\repository\ReferenceNetStandard20Library\ReferenceNetStandard20Library.csproj]
  Program.cs(8,27): error CS0012: The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\home\site\repository\ReferenceNetStandard20Library\ReferenceNetStandard20Library.csproj]

    0 Warning(s)
    2 Error(s)
```

(Let me know if you're looking for something different.)

**Comment by davidebbo** [comment] 2017-08-16 00:31
@watashiSHUN maybe the problem is that it runs msbuild 14 by default? Would it work with 15?

**Comment by davidmatson** [comment] 2017-08-16 00:38
I tried downgrading to a package that references netstandard 1.3, but that also fails, though with a different error; I'm not sure if the root cause is the same or not. (I can fork this part to a different issue if you like.)
https://github.com/davidmatson/kuduissue2521repro/tree/tryNetStandard13

```
remote: CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: 'D:\home\.nuget\System.Xml.ReaderWriter\4.3.0\ref\net46\System.Xml.ReaderWriter.dll' and 'D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\Facades\System.Xml.ReaderWriter.dll'. Remove one of the duplicate references. [D:\home\site\repository\ReferenceNetStandard20Library\ReferenceNetStandard20Library.csproj]
remote: CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: 'D:\home\.nuget\System.Text.RegularExpressions\4.3.0\ref\net463\System.Text.RegularExpressions.dll' and 'D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\Facades\System.Text.RegularExpressions.dll'. Remove one of the duplicate references. [D:\home\site\repository\ReferenceNetStandard20Library\ReferenceNetStandard20Library.csproj]
```

**Comment by davidmatson** [comment] 2017-08-16 00:41
RE: MSBuild 15:
I tried running that from Kudu Console but couldn't find a v15 subdirectory where v14 is.

```
D:\Program Files (x86)\MSBuild>where msbuild
D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe

D:\Program Files (x86)\MSBuild>dir
...
06/06/2017  04:25 AM    <DIR>          .
06/06/2017  04:25 AM    <DIR>          ..
06/06/2017  04:12 AM    <DIR>          12.0
06/06/2017  04:18 AM    <DIR>          14.0
06/06/2017  03:44 AM    <DIR>          Microsoft
06/06/2017  04:25 AM    <DIR>          Microsoft.Cpp
               0 File(s)              0 bytes
               6 Dir(s)   3,167,887,360 bytes free
```

**Comment by davidebbo** [comment] 2017-08-22 04:30
It's in a different place, though it's not the final v15 yet: `D:\Program Files (x86)\MSBuild-15.3-preview\MSBuild\15.0\Bin`.

@watashiSHUN is there an app setting someone can use to switch to this build without hard coding the path?

**Comment by davidmatson** [comment] 2017-08-23 20:37
Any thoughts on when the final v15 will be available? I tried running the preview version manually when I ran into a related problem, but it didn't work out.

**Comment by watashiSHUN** [comment] 2017-08-24 21:10
We will replace preview with 15.3 with the next release

**Comment by davidmatson** [comment] 2017-08-25 17:05
Great news - thanks! Any rough estimate for the next release?-
(#2528 is another issue hitting the same root cause.)

**Comment by davidmatson** [comment] 2017-10-31 17:59
Any update on when the next release will be available? Thanks!

**Comment by davidebbo** [comment] 2017-10-31 20:16
@watashiSHUN, is that change already in?

**Comment by davidebbo** [comment] 2017-10-31 20:17
Actually, it's clear that it is, so closing.

**Comment by davidmatson** [comment] 2017-11-07 02:47
I'm still getting the error message above when I deploy the repro repository. Is MSBuild 15 there but not the default?

**Comment by watashiSHUN** [comment] 2017-11-07 03:26
@davidmatson msbuild15 is not the default builder when building [console app](https://github.com/projectkudu/KuduScript/blob/master/lib/templates/deploy.batch.dotnetconsole.template#L15)

Were you able to build use `MSBuild-15.3.409.57025` ?
if so, you can just add an app setting to your website
`MSBUILD_PATH=D:\Program Files (x86)\MSBuild-15.3.409.57025\MSBuild\15.0\Bin\MSBuild.exe`

this is (**almost**) equivalent of having msbuild15 by default
the catch is that during restore, `nuget` will go back to use `msbuild14`
but it might not matter for you, I tried on your same [repo](https://github.com/davidmatson/kuduissue2521repro)

if restore is an issue, you will need to add a custom deployment script:

> 1. pass the msbuild15.3 directory to nuget (nuget4 has dependency on it):
> `nuget.exe restore "{your .sln file path}" -MSBuildPath "%MSBUILD_15_DIR%"`
> 2. use msbuild15.3 to build and publish:
> `"%MSBUILD_15_DIR%\MSBuild.exe {your build arguments}"`

let me know if you need additional help

**Comment by davidmatson** [comment] 2017-11-07 03:29
Thanks @watashiSHUN. I think the version of MSBuild for NuGet restore will matter for most of my real-world cases.

Any thoughts on when MSBuild 15 will be used by default?

Can this issue be kept open in the meantime (since it still repros)?

Thanks,

David

**Comment by watashiSHUN** [comment] 2017-11-07 03:30
are you just building console app?

**Comment by davidmatson** [comment] 2017-11-07 03:31
Yes, I have a number of repos that build console apps (which run as continuous web jobs).

**Comment by davidmatson** [comment] 2017-11-07 03:37
And yes, the build does succeed if I run MSBuild.exe manually from the Kudu console specifying the full path to the new version.

**Comment by jvano** [comment] 2024-04-29 10:19
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Closed by jvano** 2024-04-29 10:19 UTC
