### ISSUE TITLE
Some folders are not visible in KUDU

### ISSUE THREAD

**Issue by vikguptaMS** [projectkudu/kudu#2595] opened 2017-10-12 11:11 UTC
Hi Team,

Some folder are not visible in KUDU.
Lets say I have 20 folders and only 10 folders are visible and remaining folders are not visible.
KUDU loads folder first and then files. I can see some folder and then it is showing files but remaining folders are not visible.

When I do "CD Folder Name" I am able to get into that folder but it is not visible in KUDU.
Can you please check and help.

Regards,
Vikas

**Comment by davidebbo** [comment] 2017-10-12 14:22
One possible explanation is that you have so many files/subfolders in this folder that it reaches the limit of what Kudu displays is the UI. Can you do a `dir` and get the number of files? I think limit is 250, though I'd need to double check.

**Comment by davidebbo** [comment] 2017-10-12 14:23
Actually limit is 300 ([code](https://github.com/projectkudu/kudu/blob/0fe7fbe12ce4786aaefa233da6b2c4272578b5f4/Kudu.Services.Web/Content/Scripts/FileBrowser.js#L256)).

Closing as I assume that's what you're seeing, but if you have fewer items and don't see folders, we can reopen.

**Comment by vikguptaMS** [comment] 2017-10-12 15:30
Hey, can you please re open this.

I have total 299 items in the folder but still folder is not visible.
Let me tell you one more thing.
KUDU display folder first and then files but in my case it is not displaying all folders and started displaying files after some folders.

**Comment by davidebbo** [comment] 2017-10-12 15:44
As a test, if you move all the files somewhere else, do the folders all show up?

**Comment by vikguptaMS** [comment] 2017-10-12 15:55
Yes, I can see all those folders using FTP
and my application is working which can't work without those folders

**Comment by vikguptaMS** [comment] 2017-10-12 16:10
I want to understand whether there is some limitation on displaying number of folders or not?

**Comment by davidebbo** [comment] 2017-10-12 16:24
I think you misunderstood my previous question, which was not related to FTP:

> As a test, if you move all the files somewhere else, do the folders all show up?

This will help isolate.

**Comment by vikguptaMS** [comment] 2017-10-13 04:45
Thanks for your response, Let me try this.
While I am checking this, can you please also check whether there is some limitation on displaying the number of folders(not files)?

**Comment by vikguptaMS** [comment] 2017-10-13 05:47
Hi,
I tried it.. at a time KUDU display only 299 files and if I will upload more files then it will start disappearing some folders/files.
I uploaded folders with name 1 to 100 and text file with name 1 - 200... when I uploaded files with name 201 to 220 then it was not showing some folders from 90 to 99.. when I deleted some text files it started displaying those folders.. please let me know if this information helps.

**Comment by davidebbo** [comment] 2017-10-13 13:59
Thanks for confirming. You are clearly hitting the 300 item display limit, so this is by design.

**Comment by vikguptaMS** [comment] 2017-10-16 10:09
Hi Davidebbo,

Thanks for your response.
Are you planning to display all items in future?
If the order of loading is Folders first and then files, Why folders are missing after adding a new file?
Is there any way we can see all folders?

Regards,
Vikas

**Comment by davidebbo** [comment] 2017-10-16 15:33
The reason is doesn't display all is that perf becomes really bad with large folders. Fixing this would mean adding some kind of paging support, and there is no current plan to do this. The order is whatever the file system returns, which is not necessarily folders first.

**Comment by TCBroad** [comment] 2017-12-05 12:09
There is a further issue with this: when you are in a subfolder from root folder containing more than 299 items, it doesn't sync the file/folder view with the path on the command line.

![image](https://user-images.githubusercontent.com/1906419/33606361-23d8f5f4-d9b5-11e7-8759-da8b15fa8af0.png)

**Comment by watashiSHUN** [comment] 2017-12-05 19:28
@vikguptaMS you can personalize your display limit for the browser, we have it documented in kudu wiki [here](https://github.com/projectkudu/kudu/wiki/Kudu-console#navigate-around-using-the-folder-ui) ( +https://github.com/projectkudu/kudu/issues/2226 for the reference)

**Comment by watashiSHUN** [comment] 2017-12-05 20:22
@TCBroad I want to confirm that this only happens if you `cd` into a subfolder (using the command line) that is not displayed?

**Comment by TCBroad** [comment] 2017-12-06 12:53
@watashiSHUN Yes this only happen when using `cd`, and into a non-visible folder. if I increase the limit using the method you suggested, I can click or cd into all the folders as expected

**Comment by CarlosOnline** [comment] 2018-04-15 07:34
Please add a query param like ?maxViewItems=1000 - the window.localStorage.setItem('maxViewItems', 1000) is really in convenient.

**Comment by mekamata** [comment] 2018-10-09 02:09
Hi, I'm css engineer. Could we change display order of files and folder in Kudu site in future? (like sorting support) The customer could not see newest file by default, because there are more files than 300 and the files are displayed in date ascending order.

Regards,
Mei

**Closed** 2024-04-29 10:18 UTC
