### ISSUE TITLE
Resx doesn't work on Azure Webjobs deployed with git

### ISSUE THREAD

**Issue by subgurim** [projectkudu/kudu#1503] opened 2015-03-19 13:18 UTC
Hi!

I'm using an Azure Webjob to send localized emails (en, es, fr...). The webjob is deployed using git.

The problem is that the resx dll's aren't copied to the app_data/jobs/continuous/MyWebJob folder, so the neutral resx's are used.

**If I deploy it by compressing the local bin directory and uploading the resulting zip everything works ok**, the texts are in the correct language.

It seems that those culture folders (/en, /es, /fr) aren't copied for any reason from a git deployment.

Thanks!

**Comment by davidebbo** [comment] 2015-03-19 15:56
Could you [share a test repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that demonstrates the problem? That will help us investigate. Thanks!

**Comment by subgurim** [comment] 2015-03-24 18:30
That's a really good idea!!

Here is it: https://github.com/subgurim/WebJobLocalizationTests

I've added some screenshots ;)

Thanks!

**Comment by davidebbo** [comment] 2015-03-24 21:01
When I build this on a local machine, I end up with an `es` folder under `WebJobLocalizationTests\bin\Debug`. And when I push your repo to Kudu, I end up with exactly the same thing under `D:\home\site\wwwroot\app_data\jobs\continuous\deployedJob`.

So I'm not seeing anything different in the Kudu behavior.

**Comment by davidebbo** [comment] 2015-03-24 21:34
BTW, I'm not seeing the screenshots you mentioned.

**Comment by subgurim** [comment] 2015-03-24 21:42
Hi!!

I'm so sorry!!! I had a big confusion. I have two projects, a web project and a console project. I use the "add an existing project as a webjob" to add the console project to the website and this is what is failing.

I'm really sorry, please let me change the test repo so you only need to clone it.

**Comment by davidebbo** [comment] 2015-03-24 21:44
One thing you should try first is a 'Publish To File System', as described [here](https://github.com/projectkudu/kudu/wiki/Make-sure-site-correctly-deploys-locally#locally-testing-your-deployment). That will help isolate. Thanks!

**Comment by subgurim** [comment] 2015-03-24 21:58
Ok I did it, I've added a website and added the console as a WebJob.

This time I published using "publish azure website" instead of publishing it using git. Same problem :(

Here are the screenshots: https://github.com/subgurim/WebJobLocalizationTests

Thanks!

**Comment by davidebbo** [comment] 2015-03-24 22:00
Did you try the Publish To FIle System I mentioned in my previous mail? If the same issue happens there, then at least we know it's a pure VS issue not related to Kudu. Thanks!

**Comment by subgurim** [comment] 2015-03-24 22:23
Wow!

You were right!

Publishing on file system produces the same problem!!

![filesystem-webjob](https://cloud.githubusercontent.com/assets/3378649/6814192/b436d816-d27c-11e4-92d0-59e559263b0f.png)

:(

Any advice of what can I do?

**Comment by davidebbo** [comment] 2015-03-25 00:29
@bradygaster: this looks like a VS issue in the WebJobs deployment logic. Where is the best place to track it? Thanks!

**Comment by subgurim** [comment] 2015-04-08 17:37
Please excuse my insistence but do you know somewhere to report this problem?

**Comment by bradygaster** [comment] 2015-04-08 17:52
@subgurim you'd want to report it to my team, the Web Tools Extensions team. I'll take this GitHub conversation to my team so we can triage. I think there's a simple fix for this particular scenario. We are working on a larger, more long-term resolution to some of the CI stories with WJ deployments, but I think the team will be able to provide a quick solution for you in the meantime. Give me a day or two (max) to sync with the team and I'll update this post.

**Comment by subgurim** [comment] 2015-04-08 17:57
Great!! Thank you very much. I wait for an answer here.

**Comment by subgurim** [comment] 2015-04-15 09:01
Hi @bradygaster! How's the matter? Have you managed to solve the problem? Is there any better place to talk about this?

Thanks!

**Comment by bradygaster** [comment] 2015-04-15 19:12
@subgurim I don't have more information yet. I'll continue to follow up. We do have a large swath of WebJobs improvements that are related to the VSO side (not the GitHub side) that we're going to be making, but it won't be until the summer as it will require some coordination on the VSO team's side; those conversations are continuing. I'm going to ask one of our devs to take a quick look at this thread for more insight.

**Comment by bradygaster** [comment] 2015-04-15 20:31
@subgurim i just heard back from the dev team. Could you try updating your WebJobs publishing NuGet to the newly-released 1.0.3 version and let me know if that fixes the issue? The NuGet is here: https://www.nuget.org/packages/Microsoft.Web.WebJobs.Publish/

**Comment by subgurim** [comment] 2015-04-17 07:27
Hi @bradygaster, 

First of all thanks for your help. 

Unfortunately 1.0.3 version doesn't solve the problem. 

Just to put on record I want to remind you that this is not a "git" problem. The same problem happens if I "publish" the website to the "file system".

On 1.0.3 some changes happens, let me explain it with images.

This was the publish result of a website that point to a webjob (1.0.2):


![](https://raw.githubusercontent.com/subgurim/WebJobLocalizationTests/master/WebJobLocalizationTests/Screenshots/FileSystem-WebJob.png)

This is the current publish result of a website that point to a webjob (1.0.3):
![error-webjoblocalization-1 0 3](https://cloud.githubusercontent.com/assets/3378649/7197452/a7c9139c-e4e1-11e4-8dae-172b43419c2f.png)

As you can see a *.resources.dll appears now

And this is the compilation result of the webjob (NOT the website publish result):
![error-webjoblocalization-webjobcompilation](https://cloud.githubusercontent.com/assets/3378649/7197514/5243b106-e4e2-11e4-9ff3-3f3b6f811767.png)

Inside the "es" directory is the *.resources.dll file.


**IMPORTANT**
If I get the result of a website that point to a webjob (1.0.3, second image), and I manually create an "es" directory and I cut&paste the *.resources.dll file to the "es" directory... it works!!! But it's not a good solution because it will fail if I work with more than 2 languages

I've updated the repository with the new changes: https://github.com/subgurim/WebJobLocalizationTests

Do you think it would be possible to finish to fix the problem?

¡¡¡Thanks!!!

**Comment by bradygaster** [comment] 2015-04-17 21:04
@subgurim we took a long look at this and have a fix. I don't want you to wait for the fix to be unblocked for for now, here's a workaround. Please let me know if this works/doesn't. Full fix should be out soon. 

Replace these lines: 

<ItemGroup>
      <FilesToPublish Include="$(OutputPath)**\*.*" Exclude="$(OutputPath)$(AssemblyName).vshost.*"/>
    </ItemGroup>

    <ItemGroup>
      <WebJobProjectOutputs Include="%(FilesToPublish.FullPath)"/>
    </ItemGroup>

With this:

<ItemGroup>
      <WebJobProjectOutputs Include="$(OutputPath)**\*.*" Exclude="$(OutputPath)$(AssemblyName).vshost.*"/>
    </ItemGroup>

**Comment by subgurim** [comment] 2015-04-20 08:17
Hi @bradygaster,

I am very grateful for your help, but still not working :(

Now it gives me this error: "Copying file bin\Release\es\WebJobLocalizationTests.resources.dll to obj\Release\Package\PackageTmp\app_data\jobs\triggered\WebJobLocalizationTests\WebJobLocalizationTests.resources.dll failed. Could not find file 'bin\Release\es\WebJobLocalizationTests.resources.dll'." on Project MvcApplication1

The same error occurs both publishing to file system and deploying to azure via git.

I've pushed this changes to the repo: https://github.com/subgurim/WebJobLocalizationTests

Thanks!!

**Comment by bradygaster** [comment] 2015-04-20 17:49
We're investigating - the fix we suggested will work if you're publishing the WJ directly from VS, but we're investigating the fix for publishing it with the Web App. Will update shortly.

**Comment by bradygaster** [comment] 2015-04-20 17:58
@subgurim could you try this and update the webjobs.console.targets file one more time?

Lines 199-205, replace:

    <ItemGroup>
      <FilesToPublish Include="$(OutputPath)**\*.*" Exclude="$(OutputPath)$(AssemblyName).vshost.*"/>
    </ItemGroup>

    <ItemGroup>
      <WebJobProjectOutputs Include="%(FilesToPublish.FullPath)"/>
    </ItemGroup>

WITH:

    <ItemGroup>
      <FilesToPublish Include="$(OutputPath)**\*.*" Exclude="$(OutputPath)$(AssemblyName).vshost.*"/>
    </ItemGroup>

    <ItemGroup>
      <WebJobProjectOutputs Include="%(FilesToPublish.FullPath)">
          <TargetPath>%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
      </WebJobProjectOutputs>
    </ItemGroup>

**Comment by subgurim** [comment] 2015-04-20 19:52
Awesome!! It works for me on the test solution.

During the next days I´ll apply the update to my productions webapps.

I'm grateful to you and the development team for giving me the customized solution to the problem.

Thanks!

**Comment by thedmi** [comment] 2015-07-08 06:25
For others ending up here and trying to solve the same problem: The fix @bradygaster describes above involves patching the file `webjobs.console.targets` in the `Microsoft.Web.WebJobs.Publish` nuget package.

**Comment by thedmi** [comment] 2015-07-08 06:28
@bradygaster This is still not fixed in the nuget package. Patching it on the client side is a big hack when using automatic package restore. The fix seems simple, so it would be nice if you could update the nuget package!

**Comment by bradygaster** [comment] 2015-07-08 17:39
I've forwarded the suggestion over to the devs, who are actually working on some improvements in this area for an upcoming release (timeline is "very soon" - sorry I can't be more articulate about release dates).

**Comment by fakedevil** [comment] 2015-10-13 04:07
Any update on this issue? I agree with @thedmi, this blocks end users who does package restore (ME!) :(

**Comment by bradygaster** [comment] 2015-10-13 15:16
@fakedevil do you mean update the project reference to pull down the updated 1.0.7 package? I thought, as you called out, that the 1.0.7 package has the fix for the initial issue. So is your comment that we should include 1.0.7 in the official templates, or is there something else going wrong?

**Comment by fakedevil** [comment] 2015-10-13 16:11
Yup update package to the latest 1.0.7 and the issue is resolved. I think we should close this issue and say its resolved from whichever version onwards.

**Closed** 2015-10-13 17:18 UTC
