### ISSUE TITLE
.deployment project and command cannot be used together?

### ISSUE THREAD

**Issue by lzl124631x** [projectkudu/kudu#2756] opened 2018-04-27 06:40 UTC
# Repro steps

## Project structures.
[repo](https://github.com/lzl124631x/liuzhenglai)
```
|--- back-end
|--- front-end
|--- .deployment
```
I want to deploy the node project in front-end folder. `cd front-end & npm install & npm start`

## Case 1
```
[config]
project = front-end
```
Log:
```
remote: Preparing deployment for commit id 'c70e73cb3e'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling node.js deployment.
remote: KuduSync.NET from: 'D:\home\site\repository\front-end' to: 'D:\home\site\wwwroot'
remote: Copying file: '.babelrc'
...
remote: Invalid start-up command "npm run build && node app.js" in package.json. Please use the format "node <script relative path>".
remote: Looking for app.js/server.js under site root.
remote: Using start-up script app.js
remote: Generated web.config.
remote: Selected node.js version 8.11.1. Use package.json file to choose a different version.
remote: Selected npm version 5.6.0
remote: Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
remote: Finished successfully.
remote: Running post deployment command(s)...
remote: Deployment successful.
```
In the console
```
> ls
D:\home\site\wwwroot
app.js
build
config
iisnode.yml
index.html
node_modules
package-lock.json
package.json
src
static
test
web.config
```
I can see the `index.html` but if I visit `https://lzl.azurewebsites.net` I only got
```
lzl.azurewebsites.net is currently unable to handle this request.
HTTP ERROR 500
```

I changed start script to be "node app.js" but still doesn't work. Seems the website is not running.

```
remote: Using start-up script app.js from package.json.
remote: Generated web.config.
remote: Selected node.js version 8.11.1. Use package.json file to choose a different version.
remote: Selected npm version 5.6.0
remote: Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
remote: ..............................................................................................
remote: up to date in 102.822s
remote: Finished successfully.
remote: Running post deployment command(s)...
remote: Deployment successful.
```

## Case 2
```
[config]
project = front-end
command = npm install & npm start
```
Error:
```
remote: Running custom deployment command...
remote: Running deployment command...
remote: ..
remote: npm WARN enoent ENOENT: no such file or directory, open 'D:\home\site\repository\package.json'
remote: npm WARN repository No description
remote: npm WARN repository No repository field.
remote: npm WARN repository No README data
remote: npm WARN repository No license field.
remote: ..
remote: npm ERR! Windows_NT 10.0.14393
remote: npm ERR! argv "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\3.10.8\\node_modules\\npm\\bin\\npm-cli.js" "start"
remote: npm ERR! node v6.9.1
remote: npm ERR! npm  v3.10.8
remote: npm ERR! path D:\home\site\repository\package.json
```
---
## Case 3
```
[config]
command = cd front-end & npm install & npm start
```
I got:
```
An unknown error has occurred. Check the diagnostic log for details.
```
Activity Log:
```
Command: cd front-end & npm install & npm start
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
```

# Debug your Azure website remotely.
web app name `lzl` resource group `lzl`.

**Comment by watashiSHUN** [comment] 2018-04-27 19:43
If you specify "command", "project" will not be considered (see **line number** below).
https://github.com/projectkudu/kudu/blob/1e7bd173b98079312b1e9ca9dccda3fa55b52555/Kudu.Core/Deployment/Generator/SiteBuilderFactory.cs#L33-L37
https://github.com/projectkudu/kudu/blob/1e7bd173b98079312b1e9ca9dccda3fa55b52555/Kudu.Core/Deployment/Generator/SiteBuilderFactory.cs#L48-L53
Usually kudu will decide what to do during build and deployment when code is uploaded, user can somewhat influence the process (ie tell kudu where the project folder is) but if you provide "command" it completely override kudu's decision making logic and we blindly run what you specifies

**Comment by davidebbo** [comment] 2018-04-27 19:46
Closing since this is by design.

**Closed by davidebbo** 2018-04-27 19:46 UTC

**Comment by watashiSHUN** [comment] 2018-04-27 19:48
I suspect case1 failed because you also need to deploy the backend? its hard to tell since we don't have information about your project, if you want to customize the build and deployment process, you can put a series command in a script file, see example [here](https://github.com/watashiSHUN/functionAppGitDeployment/commit/54475515da0ca8f6479020b24cb73bf7493f64fe)

**Comment by lzl124631x** [comment] 2018-04-30 02:41
@watashiSHUN  Thanks for you reply. 

> I suspect case1 failed because you also need to deploy the backend? 
No, running the front-end express server is not dependent on the back-end.

[This](https://github.com/lzl124631x/liuzhenglai) is the repo. The front-end has a independent express server. The [package.json](https://github.com/lzl124631x/liuzhenglai/blob/master/front-end/package.json) of front-end.  `npm run build` will run some webpack building and `node app.js` will start the server. Kudo only supports `node <script>` syntax in `start` script. So my start script `npm run build && node app.js` doesn't work.

Is there a way to support or workaround it? I'm not familar with scripting in cmd. If there is no other way I'll definitely do cmd scripting.

**Comment by lzl124631x** [comment] 2018-04-30 03:07
@watashiSHUN  I tried to use the powershell script. See this [commit](https://github.com/lzl124631x/liuzhenglai/commit/c235e9f696fecd8c8379853bbad05a2400ca526e)

I got the following error:
```
remote: Found package.json
remote: Running `npm install`
remote: .................................................................
remote: up to date in 75.631s
remote: Running `npm start`
remote: npm WARN lifecycle The node binary used for scripts is D:\Program Files (x86)\nodejs\6.9.1\node.exe but npm is using D:\Program Files (x86)\nodejs\8.11.1\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
remote:
remote: > liuzhenglai.com@1.0.0 start D:\home\site\wwwroot
remote: > node app.js
remote:
remote: ....
remote: events.js:160
remote:       throw er; // Unhandled 'error' event
remote:       ^
remote:
remote: Failed exitCode=1, command="D:\Program Files (x86)\nodejs\8.11.1\node.exe" "D:\Program Files (x86)\npm\5.6.0\node_modules\npm\bin\npm-cli.js" start --production
remote: Error: listen EACCES 0.0.0.0:80
remote: An error has occurred during web site deployment.
```

I met this issue before so I added `let PORT = process.env.PORT || 80;` and `process.env.PORT` worked before. But this time the port fell back to `80` again. What should I do?

**Comment by watashiSHUN** [comment] 2018-05-01 01:15
I submit a temporary [PR](https://github.com/lzl124631x/liuzhenglai/pull/1) which should unblock you for now

here are some helpful thoughts:
1. for case1, the issue is revealed at `D:\home\LogFiles\Application\logging-errors.txt` from you kudu conole, I think you installed expressjs globally in your machine but forget to include in your `project.json` 
![image](https://user-images.githubusercontent.com/6531400/39457287-a89970ca-4ca1-11e8-9bf6-89c494a33a7a.png)
2. your build and deployment process can be broken down to `npm install`(restore) and `npm run build`(build), by default kudu will run `npm install --production` since we don't want to bring all the test frameworks to your production site...however, given that you need to run `webpack` when publishing, you need to move all related package refs from `devDependencies` to `dependencies` in order to use the default template

**Comment by lzl124631x** [comment] 2018-05-01 21:44
@watashiSHUN 

> If you specify "command", "project" will not be considered.

Highly recommend adding it into [this wiki](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script). We can't expect user to read through the code. This could save user's time. Thanks a lot.

**Comment by lzl124631x** [comment] 2018-05-01 22:49
@watashiSHUN 

> the issue is revealed at D:\home\LogFiles\Application\logging-errors.txt from you kudu conole

Thanks for pinpointing this issue! Really appreciate it. I think I didn't see error messages related to `D:\home\LogFiles\Application\logging-errors.txt`, so I didn't figure it out that the `node app.js` actually failed. But weird that it told me `listen EACCES 0.0.0.0:80` so I thought express ran successfully but failed to access port `80`.
