### ISSUE TITLE
x64 version of dotnet when x64 platform is set in portal

### ISSUE THREAD

**Issue by am11** [projectkudu/kudu#2288] opened 2017-01-06 22:43 UTC
In Azure portal, I set platform to x64 in the application settings. Then added `"platform": "x64"` under "buildOptions" in aspnet-core app's project.json file (along with `win7-x64` RID). Our app is targeting SDK `"1.0.0-preview2-003121"`. After the deployment, I received `HTTP Error 502.5 - Process Failure`. On Kudu's CMD, I ran the executable under `d:\home\wwwroot` and received: 

> An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

searched this error on related repos, which led me to: https://github.com/aspnet/KestrelHttpServer/issues/1118 suggesting that we need to have dotnet.exe x64 in PATH before x86. Unfortunately, we don't have x64 bit available on Azure websites (`dir "D:\Program Files"` vs `dir "D:\Program Files (x86)"`).

To overcome this shortcoming, I have installed dotnet x64 at `D:\home\site\deployments\tools` like:

```cmd
cd D:\home\site\deployments\tools

curl -O https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-003121/dotnet-dev-win-x64.1.0.0-preview2-003121.zip

unzip dotnet-dev-win-x64.1.0.0-preview2-003121.zip
```

It would be very much appreciated if, in addition to x86 dontet-cli, we receive x64 counterpart installed (with all the SDK versions available for x86) out of the box, so we don't need to install in every App Service (we have seven dedicated services for the affected app). Also, if possible, would be nice if this transition in PATH (dotnet-x64 before dotnet-x86 and viceversa) happen when we change the bitness in portal.

Thanks.

**Comment by davidebbo** [comment] 2017-01-07 01:57
Indeed, the need for 64 bit has come up, and it's something we need to look at.

**Comment by davidebbo** [comment] 2017-01-07 18:33
Talking to @kirillg (from DocDB team), it's *supposed* to still work with 32 bit, albeit a bit slower in some scenarios.

**Comment by am11** [comment] 2017-01-07 18:45
@davidebbo, @kirillg, we were hitting the following `NotSupportedException` at `CreateDocumentQuery` callsite:

> Partition routing information cannot be extracted from the query when running in a 32-bit preferred process. To complete your query and avoid this exception, uncheck the "Prefer 32-bit" option in your project properties window, on the Build tab.

**Comment by kirillg** [comment] 2017-01-10 18:21
@am11, which .Net Core DocumentDB NuGet version are you using?

**Comment by rnagpal** [comment] 2017-01-10 18:32
@am11 Also is this a single partition collection or a partitioned collection?
Can you paste a sample of the DocDB query that is failing with this error.

Are you using the .NET Core SDK for DocumentDB(1.0.0) or the .NET Framework SDK(1.11.0) in your application?

**Comment by am11** [comment] 2017-01-10 19:13
@kirillg, we are using .NET Framework v4.5.1 and DocuemntDB is v1.11.0.

@rnagpal,

It is a single partitioned collection, but our base class supports both single and partitioned collections to engage various services. All the other consumers of base are x64 Cloud Services.

Nonetheless, this exception emerged in web application, as we upgraded the base project to v1.11.0  and some minor unrelated code changes in base class. This web application (ASP.NET Core, TFM net451) has been running since early 2016 and was building as a 32-bit process on Azure App Service.  By installing `dotnet.exe` x64 in `deployments/tools` directory (which is already in PATH), our auto-deployment from GitHub is now compiling the x64 web-application and the exception has been disappeared.

> Can you paste a sample of the DocDB query that is failing with this error.

We are calling `CreateDocumentQuery<Document>(selfLink, new FeedOptions{MaxItemCount=1}, docId)` on an instance of `Microsoft.Azure.Documents.Client.DocumentClient` in the base. I suppose it generates a pretty basic `SELECT` query under the hood in this case.

**Comment by kirillg** [comment] 2017-01-10 19:47
@am11, just to confirm you're using the DocumentDB nuget package for the Full .Net framework inside a .Net Core web app? 

Could you instead use the DocumentDB .NET Core NuGet? https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core

**Comment by am11** [comment] 2017-01-10 19:54
@kirillg, these terminologies since .NET Core are pretty confusing. :)

ASP.NET Core MVC can run on full .NET Framework as well as .NET Core.

We are using .NET Framework v4.5 TFM.

(TFM = Target Framework Moniker)

**Comment by rnagpal** [comment] 2017-01-10 22:55
@am11 We found the root cause of the regression in v1.11.0 of .NET Framework SDK and we will be releasing an update pretty soon but if you use our .NET Core DocumentDB package that Kirill pointed out, this issue will NOT repro. The .NET Core version of DocumentDB SDK is fully API compatible with the .NET Framework version and shares most of the code, so I'd recommend using our .NET Core SDK for DocumentDB portion of your app. But if you have to stick with .NET 4.5 for some reason, then you cannot use the .NET Core version.

**Comment by rnagpal** [comment] 2017-01-11 05:53
@am11 Until we release a hotfix for this, you have several options:

1. Use SDK version 1.10.0 which will not have this issue of running your query against a single partition on a 32 bit web application. Note that we always had the requirement of 64 bit when using a cross partition query(in case of partitioned collection case). 32 bit app should work for a single partition query and we will fix that soon.

2. Compile/Deploy your Web application as 64bit which you seem to have already done and confirmed that you don't see this error. 

3. Use the async version of the DocumentQuery instead of using the sync versions. This includes calling .FirstOrDefault() or .ToList() on the query. For example converting the following query:
var query = client.CreateDocumentQuery<Family>(documentCollectionUri).AsEnumerable();
 foreach (var family in query )
            {
                // process each family
            }
To:
var query = client.CreateDocumentQuery<Family>(documentCollectionUri).AsDocumentQuery();
            while (query.HasMoreResults)
            {
                var feedResponse = await query.ExecuteNextAsync<Family>();
                foreach (var family in feedResponse)
                {
                    // process each family
                }
            }

Please let me know if you have any comments.

**Comment by rnagpal** [comment] 2017-01-20 00:47
@am11 We have now fixed that 32-bit issue in our .NET SDK 1.11.2 release so there is no requirement of 64 bit anymore using DocumentDB SDK, though we recommend using 64-bit host processing for improved performance.

**Comment by am11** [comment] 2017-01-20 00:55
@rnagpal, thanks a lot for the information and follow-ups and sorry for not reverting earlier. I moved on to another project at company after employing the dontet-x64 workaround in Kudu.

Earlier, I discussed with the members of our backend team, they suggested that this predicament doesn't warrant the changes in their base class, given all the rest of our services have bitness set to 64. 

Cheers and our kudus to @rnagpal, @kirillg and the team for fixing the issue promptly! 👍 🎉

**Closed** 2017-11-07 20:21 UTC

**Comment by bojanrajkovic** [comment] 2017-12-02 03:30
How did you accomplish this workaround? I'm trying to use a native library that only has a 64-bit version. It's crazy that all this time in, only 32-bit .NET Core is available.

**Comment by am11** [comment] 2017-12-02 09:50
> It's crazy

That it is. We get OOTB installation of x86 & x64 variants when it comes to Ruby, Python, node.js and many other frameworks, but for .NET Core it's only x86. If there is an issue in having both on the system, then it should be only x64 instead or user should have a choice. In Azure Portal -> AppService -> Settings, if we change the architecture to x64, it has no impact on .NET Core (dotnet-cli remains x86)..

> workaround

My initial workaround (see top comment) was do download dotnet-sdk in x64, and put it in PATH as per Kudu documentation; `D:\home\site\deployments\tools` directory.
The direct download links to the SDK are available in release notes, f.ex: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.3.md

**Comment by Oceanswave** [comment] 2018-01-07 19:18
Came across this trying to run a .net core Azure Function with x64 dependencies. Thanks to OP for describing a workaround, but the fact that this is still an issue is aggravating.
