### ISSUE TITLE
Azure App Service not building Web Application project with Code Analysis enabled

### ISSUE THREAD

**Issue by jonsagara** [projectkudu/kudu#2223] opened 2016-11-09 22:25 UTC
Hello,

Today, when trying to set up a build for a VS2015 Web Application project that has Code Analysis enabled, I noticed that the deployment from Github failed. Here is the entire "Running deployment command..." log:
[RunningDeploymentCommand.txt](https://github.com/projectkudu/kudu/files/582005/RunningDeploymentCommand.txt)

The relevant bit is here:

```
D:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could not find rule set file "ManagedMinimumRules.ruleset". [D:\home\site\repository\src\WebProjectWithCodeAnalysis\WebProjectWithCodeAnalysis.csproj]

  WebProjectWithCodeAnalysis -> D:\home\site\repository\src\WebProjectWithCodeAnalysis\bin\WebProjectWithCodeAnalysis.dll
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(289,5): error : MSBuild could not locate the Code Analysis tool at ''. If MSBuild is being run from within the "Visual Studio Command Prompt", specify the path to the Code Analysis tool by setting the FXCOPDIR environment variable. [D:\home\site\repository\src\WebProjectWithCodeAnalysis\WebProjectWithCodeAnalysis.csproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\src\WebProjectWithCodeAnalysis\WebProjectWithCodeAnalysis.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d408edaa14d4a3";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\src\\"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.51102.2512\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

Here's a sample project that I used to reproduce the issue in a brand new App Service that I just created:

[WebProjectWithCodeAnalysis](https://github.com/jonsagara/WebProjectWithCodeAnalysis)

From our side, as far as I can tell, we didn't change anything. I only noticed this issue because I tried to deploy an existing branch to a new environment, and it failed. Prior to today, we've had no problems deploying this branch.

Also, the sample project above is just a plain ASP.NET WebApi application project created with VS2015, targeting .NET 4.6. The only change I made to it was to enable Code Analysis for both Debug and Release. Deploying it to a newly created App Service fails with the above-mentioned error.

Has something changed with how Code Analysis works during git deployments in an Azure App Service?

Thanks,

Jon

**Comment by nulltoken** [comment] 2016-11-10 15:55
We're encountering the exact same issue.

**Comment by nulltoken** [comment] 2016-11-10 15:58
ping @davidebbo 

![image](https://cloud.githubusercontent.com/assets/92363/20183800/d70532a0-a766-11e6-9839-f4a7de67ef33.png)

**Comment by davidebbo** [comment] 2016-11-10 16:09
Yes, looks like we do have a regression here. @ahmelsayed we need to get to bottom of this.

**Comment by ahmelsayed** [comment] 2016-11-10 20:25
This should be fixed now. Please give it another try

**Closed by ahmelsayed** 2016-11-10 20:25 UTC

**Comment by jonsagara** [comment] 2016-11-10 20:40
Confirmed fixed. Thank you for the quick response!

**Comment by davidebbo** [comment] 2016-11-10 21:40
Glad that worked! Sorry Jon and Em for the break. Sometimes we move a little too fast :)

**Comment by nulltoken** [comment] 2016-11-14 16:55
@ahmelsayed @davidebbo 

![image](https://media.giphy.com/media/3oz8xyqQtObiZ46RYQ/giphy.gif)
