### ISSUE TITLE
Unable to install windows-build-tools

### ISSUE THREAD

**Issue by os1r1s110** [projectkudu/kudu#2169] opened 2016-10-06 18:18 UTC
Hi, I'm trying to use node sharp package to resize images on the fly but before I can install it, I need node-gyp running on the server and I tried to install it following these instructions: https://github.com/nodejs/node-gyp 

I was able to install the node-gyp package, but when it comes to " windows-build-tools: npm install --global --production windows-build-tools" section of the following page "https://github.com/nodejs/node-gyp", I get an error stating that I need to start the cmd prompt or powershell with admin privileges, but I can't do that on kudu's web interface. 

Is there any way to accomplish what I want or any other method to be able to use sharp package on azure along with my asp.net core application?

**Comment by davidebbo** [comment] 2016-10-06 23:37
You're showing the same package name when you refer to the 'Windows part'. Maybe a typo?

Can you paste the exact commands that you run and their output?

**Comment by os1r1s110** [comment] 2016-10-07 00:50
Yeah it was indeed a typo, fixed, thanks

**Comment by davidebbo** [comment] 2016-10-07 00:53
You can't install anything machine level on an Azure Web App, so this command won't work. However, I'd expect the tools to already be available.

Note that node-gyp is only supported on Web Apps running on the Basic tier or higher.

**Comment by os1r1s110** [comment] 2016-10-07 11:55
Oh, that explains why it doesn't work on Azure itself, but I don't understand why I didn't get an error to tell me I had insufficient permissions to install it....

 But even if I had the rights to install on the machine, I'm still not sure it would work on Azure App Service (web app) as stated in this link: https://azure.microsoft.com/en-us/documentation/articles/nodejs-use-node-modules-azure-apps/ 

"While most modules are simply plain-text JavaScript files, some modules are platform-specific binary images. These modules are compiled at install time, usually by using Python and node-gyp. Since Azure Cloud Services rely on the node_modules folder being deployed as part of the application, any native module included as part of the installed modules should work in a cloud service as long as it was installed and compiled on a Windows development system."

The package I need is sharp or lwip to resize images on the fly and as of now, I still found no way to get it to work on Azure, even if precompiled on my machine....

**Comment by davidebbo** [comment] 2016-10-07 13:11
That doc is slightly outdated, as we've seen added support for some node-gyp scenarios when running on Basic or higher.

I'll close this one since not being able to install windows-build-tools is by design. But if you run into an issue with another package that doesn't do machine global installation, go ahead and open a new issue. Make sure you specify the exact command and output that you get from Kudu Console.

**Closed by davidebbo** 2016-10-07 13:11 UTC

**Comment by os1r1s110** [comment] 2016-10-07 13:23
Would you have an idea why a precompiled node_module wouldn't work either? I am trying to find a way to make it work but I can't seem to get correct debugging messages. Anyways yeah it's good to close this thread as it's not directly related to Kudu I guess.

Thanks for your time and help!
