### ISSUE TITLE
Linux: Unable to access <app>.scm.azurewebsites.net, Service Unavailable

### ISSUE THREAD

**Issue by WayneUong** [projectkudu/kudu#2804] opened 2018-06-28 22:45 UTC
I have 7 web apps connected to a service plan. Only 2 of them are able to access their scm.azurewebsites.net sites. The rest give Service Unavailable. They all use very similar settings, as they were deployed through a copy loop using the ARM template.

**Comment by davidebbo** [comment] 2018-06-28 22:46
Are they sites where this has ever worked, or was it broken from creation time? What's one of the broken site names?

**Comment by WayneUong** [comment] 2018-06-28 22:49
The apps are docker containers and they run fine. I'm just unable to access kudu. they were just deployed an hour ago. Right now I'm getting these 2 errors:
![screen shot 2018-06-28 at 3 47 16 pm](https://user-images.githubusercontent.com/8436742/42064371-dddc01fe-7aea-11e8-87d8-7fd26c1cfc24.png)
![screen shot 2018-06-28 at 3 47 32 pm](https://user-images.githubusercontent.com/8436742/42064372-ddf8e530-7aea-11e8-90ae-febf6593569f.png)

**Comment by WayneUong** [comment] 2018-06-28 22:59
All of them just suddenly went back online now. Very strange.

**Comment by davidebbo** [comment] 2018-06-28 23:15
Adding @rramachand21 since this is Linux.

**Comment by ElanHasson** [comment] 2019-04-03 01:03
The same happened to me. I also deleted and redeployed apps with the same name multiple times.

**Comment by balag0** [comment] 2019-04-03 21:47
@ElanHasson  Could you provide more details on how you are creating the app? Looks like you are trying to create Linux Function App with AppService plan. Is that correct?
Also are you using an existing app service plan?

**Comment by ElanHasson** [comment] 2019-04-03 22:32
@balag0, I've opened a support case with Azure support and can provide it and other details to you via email.

You're correct, Linux function app and a new app plan.

I created via azure portal UI and via Visual Studio publish feature to the same end result.

**Comment by balag0** [comment] 2019-04-03 22:55
Okay. Thanks. We will follow up with you using the support case and we will close this issue for now.

**Closed by balag0** 2019-04-03 22:55 UTC
Labels: Linux

**Comment by ElanHasson** [comment] 2019-04-03 23:29
@balag0 I just got an email from them and they told me to log an issue here: https://github.com/Azure/azure-functions-core-tools/issues/ as it's in preview still.

**Comment by balag0** [comment] 2019-04-03 23:32
Okay. I will follow up there since the issue is likely unrelated to kudu. Thanks

**Comment by sijucm** [comment] 2021-03-29 12:09
I have the issue with kudu not loading (service unavailable) and my specific case is with a vnet integrated function-app. I cannot deploy the function after vnet integration (timesout after a whopping 43 minutes of Microsoftiness and gives 503 error) and I cannot even look at kudu logs because it is not working. Microsoft should focus on getting some things right instead of making the products extremely complex and they cannot handle it.

**Comment by suwatch** [comment] 2021-03-29 17:13
Please open [an App Service support ticket](http://aka.ms/CRI-WebApps) instead.

**Comment by RachidAZ** [comment] 2022-05-06 15:04
> opened

I have the same issue, SCM shows "Service Unavailable" , other function in the same function plan is working just fine (with the same exact configuration/location, just different resource groups)
