### ISSUE TITLE
Kudu console of all sites in Azure webhost plan inaccessible: Error 502

### ISSUE THREAD

**Issue by sdekock** [projectkudu/kudu#1469] opened 2015-02-16 07:43 UTC
The Kudu console in Azure for our websites recently became inaccessible.
We're getting: 502 - Web server received an invalid response while acting as a gateway or proxy server.

The site is https://ichange.scm.azurewebsites.net/

The other scm sites in the same web hosting plan also don't work.

The same error happens with WebDeploy:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets(4377, 5): error ERROR_PROXY_GATEWAY: Web deployment task failed. (Could not connect to the remote computer ("ichange.scm.azurewebsites.net") using the specified process ("Web Management Service"). This can happen if a proxy server is interrupting communication with the destination server. Disable the proxy server and try again. Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_PROXY_GATEWAY.)

**Comment by davidebbo** [comment] 2015-02-16 08:51
So you mean that it's affecting the scm site, but not the site itself?

**Comment by sdekock** [comment] 2015-02-16 09:03
The sites are working fine:
https://ichange.azurewebsites.net/ (Or via the real domain: https://ichange.eu/)

Before getting prompted for credentials.

**Comment by sdekock** [comment] 2015-02-16 09:59
Restarting the website via the Azure portal fixed the issue.

Is there any way we can see why it stopped working?

**Comment by suwatch** [comment] 2015-02-18 22:35
@sdekock Just to let you know that we are still investigating.  We can see what happened and tried to pinpoint the root cause.  Anyway, it seems like the kudu (scm) site goes into that state again.   Feel free to restart to get unblocked if you need to use kudu site.  We will update once we learn more.

**Comment by sdekock** [comment] 2015-02-18 22:44
@suwatch Thank you for investigating. We don't need the kudu site for the next couple of hours (it's almost midnight over here) so feel free to investigate. Just don't take the website itself offline please :)

**Comment by sdekock** [comment] 2015-02-18 22:59
If it can be of help: this was the same website as issue #1358

**Comment by suwatch** [comment] 2015-02-19 03:49
We have fixed #1358. For this one, it is different.   W3WP for kudu (SCM) site spinned up and crashed right away!  While we are trying to figure it out from our side, you can help us isolate.   For instance, create a new vanilla site, access SCM see if any issue.  Then start incremental change such as add NewRelic, deploy your app, ipssl, etc.   This might help reveal what step causes the issue.

**Comment by suwatch** [comment] 2015-02-20 03:43
@sdekock It turned out doing an investigation on the live site such as taking a crash dump is a bit harder than we thought and will affect your running sites.   It might be safer to try to isolate this by back tracking the below step-by-step and check SCM access as you go.  

  - Try vanilla site.   I did try this on your virtual machine and it works great.   Meaning VM and SCM bits are OK.
  - Deploy your content.
  - Turn on NewRelic.  
  - IP SSL

Let us know how it goes.

**Comment by francisrath** [comment] 2015-02-20 12:41
It think I might be affected by the same issue. The site in question is running as one of many in standard mode (we have a reserved machine for our websites), and gives me a 502 on both the site itself and Kudu.

I tried to restart the site from the management portal, but it did not change anything. Also tried stop + check that it stopped + start but still same issue.

The site in question is setech[.scm].azurewebsites.net - feel free to restart and/or poke around as it is only a test deployment so far.

**Comment by sdekock** [comment] 2015-02-20 12:58
The SCM for our site is online again without us restarting ut.

Our websites themselves were never affected. The SCM for other sites on the same hosting plans were also not always affected (we had some cases, but not always).

I'll try to reproduce, but I'm guessing it will be very hard to pinpoint because of the erratic behavior and without the ability to see error messages or crash dumps.

@suwatch If it takes the website offline for a few minutes while you take a crash dump, we don't have a problem with it. We'd prefer between midnight and 6 am UTC.

**Comment by suwatch** [comment] 2015-02-20 18:01
@francisrath we will take a look at your site and see if it is the same issue.   

@sdekock we will only do it between that time given.

**Comment by davidebbo** [comment] 2015-02-20 19:44
I'd rather not use this thread as a catch all for all WebSites issues. @francisrath if your entire site is down and not just Kudu, then it is a wider issue not related to Kudu, and this is not the right place for it. Can you please start a thread on the [forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowsazurewebsitespreview) instead? Thanks!

**Comment by francisrath** [comment] 2015-02-20 20:10
Sorry @davidebbo for kidnapping the thread :)
I have now [posted on the forum](https://social.msdn.microsoft.com/Forums/en-US/153602e5-5bda-479f-949e-dbe20b1b829d).

**Comment by suwatch** [comment] 2015-02-22 06:37
@sdekock I just got a chance to try to gather the crash dump.  Unfortunately, the SCM happened to work properly.   Did you change anything to make it working?   Anyway, I will try again tomorrow.

**Comment by sdekock** [comment] 2015-02-22 13:01
@suwatch Last deploy was 19 Feb 15 14:16 (either UTC or UTC+1, I'm not sure). We haven't touched the environment since. The SCM seems to be stable again ... maybe we should shelve the issue?

**Comment by suwatch** [comment] 2015-02-23 06:47
@sdekock I tried again and SCM access worked just fine.  I will close this for now.  Please reopen if the issue comes back.

**Closed by suwatch** 2015-02-23 06:47 UTC
