### ISSUE TITLE
Build fails when certain packages are restored by nuget v3.5

### ISSUE THREAD

**Issue by am11** [projectkudu/kudu#2173] opened 2016-10-08 16:26 UTC
Recently, we have found that Microsoft Windows Azure Media Service extension package when restored by nuget v3.5 fails to build by both msbuild and dotnet muxer.

Steps to repro:

In `d:\home`, using `cmd`:

```cmd
mkdir test && cd test
dotnet new
```

then edit `project.json` and replace the entire file contents with:

```json
{
  "frameworks": {
    "net451": {
      "dependencies": {
          "windowsazure.mediaservices.extensions": "3.3.0"
      }
    }
  }
}
```

save & close. Back in cmd, run:

```cmd
nuget restore
dotnet build

:: Error:
:: D:\home\test\project.json(5,58): error NU1001: The dependency WindowsAzure.MediaServices >= 3.3.0 could not be resolved.
```

Run `nuget` command without any parameter to check the version (in first line of output). It must be v3.5.

Lets download v3.4 (stable) and try the steps again. In `cmd`, where Unix `curl` utility is available in PATH:

```cmd
curl -o "d:\home\site\deployments\tools\nuget.exe" ^
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
```

Now running `nuget restore` followed by `dotnet build` succeeds.

**Comment by am11** [comment] 2016-10-08 16:33
@davidebbo, I think this is more of a NuGet issue as I can reproduce it with NuGet `v3.5.0.1938` locally.

**Comment by davidebbo** [comment] 2016-10-08 17:09
Thanks for opening but on their repo. I'll talk to them directly to make sure they give it attention.

**Comment by davidebbo** [comment] 2016-10-08 17:21
I just reproed it locally too. It looks like a casing issue in the lock file. In two places, the line

      "WindowsAzure.MediaServices/3.3.0": {

becomes lower case when using nuget 3.5:

      "windowsazure.mediaservices/3.3.0": {

If you change the casing, it works. Seems like a bad regression. I'll ping those guys.

**Comment by am11** [comment] 2016-10-08 17:41
Excellent! After restoring with v3.5, I replaced `"windowsazure.mediaservices/3.3.0":` with `"WindowsAzure.MediaServices/3.3.0":` in `project.lock.json` and `dotnet build` succeeded.

Thanks for discovering this workaround @davidebbo. :)

**Comment by davidebbo** [comment] 2016-10-10 00:19
Closing here since it's a nuget issue much more than kudu.

**Closed by davidebbo** 2016-10-10 00:19 UTC

**Comment by davidebbo** [comment] 2016-10-11 22:27
The media team just released windowsazure.mediaservices.extensions v3.5.2, which fixes this casing issue. So if you move to that, it should just work.

**Comment by am11** [comment] 2016-10-15 11:15
Hello @davidebbo, thank you for the follow-up. :)

Despite the fact that NuGet issue has been resolved, we get another issue with AzMediaSrv extension package v3.5.2, which apparently is unrelated to the NuGet version (reproducible with `dotnet restore`, `nuget34 restore` and `nuget35 restore`). I have filed that with steps to repro here: Azure/azure-sdk-for-media-services-extensions#31.

**Comment by davidebbo** [comment] 2016-10-16 16:20
Hopefully, they'll help figure this out!
