### ISSUE TITLE
VSTS Deployments fail during Fetching changes step

### ISSUE THREAD

**Issue by moswald** [projectkudu/kudu#2096] opened 2016-08-04 16:08 UTC
The activity log only contains:

`Failed to parse supported auth schemes: The operation identifier is not valid.\r\n`

Let me know what else you'd like me to add to this issue to help track it down.

**Comment by shrimpy** [comment] 2016-08-04 16:42
@moswald "fail during fetching changes step", do you mean it failed when you try to link a VSTS repo to a site? or it failed when a webhook try to trigger a new deployment?

i am trying to repro now, but if you can provide repro steps, that will help speed up the investigation.

**Comment by moswald** [comment] 2016-08-04 16:44
The VSTS repo is connected, and when a push is made to the triggering branch (`release` in our case), it fails immediately during the `Fetching changes` step.

**Comment by shrimpy** [comment] 2016-08-04 16:55
@moswald thanks! that means deployment failed when webhook try to trigger a new deployment.

i am not able to repro
 - setup a VSTS repo with my test site
 - wait for initial deployment is done
 -  made changes on the file from repo
 - new deployment trigger by webhook is good too 


can you provide your site name directly or [in-directly ]?(https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)

**Comment by moswald** [comment] 2016-08-04 18:31
I created a new dummy site on the same AppService Plan and it worked fine. Switching back to the original, it also worked fine. -- I don't know if my creating the new site triggered some configuration change that fixed everything or not. I'll let you know if I can reproduce the error today, else I'll close the issue as not-reproducible.

**Comment by moswald** [comment] 2016-08-05 12:04
I wish I could have reproduced it, but I never got it to happen again. I'll chalk this up to ghosts in the machine. If it should happen again I'll come back here and reopen.

**Comment by lukos** [comment] 2016-09-29 14:13
This has just happened to one of my projects. It has been deploying fine but the latest changes (just some cs and cshtml files) and I now see this error. I tried to push another empty change to retry but I get the same error. What does the error mean to us?

**Comment by davidebbo** [comment] 2016-09-29 15:25
@lukos to isolate whether the issue is specific to the Web App, does the issue also occur if you create a test Web App and set up deployment to it?

You might need to share your app name (the way @shrimpy asked earlier).

**Comment by lukos** [comment] 2016-09-29 15:43
If I point a different Azure web app to the SAME git project in VSTS, it fails
If I point a different Azure web app to a DIFFERENT git project in VSTS (previously deployed OK), it fails.

All with the same error.

Code is present in the VSTS repo.

I don't want to point the main web app to another git project because it is currently running a production system (that I was trying to update)

My test/dummy site is called loginoictest, the original problem is with the only other web app in the same App Service.

**Comment by nrandell** [comment] 2016-09-29 17:38
Just seen exactly the same. Is this something transient?

**Comment by davidebbo** [comment] 2016-09-29 19:03
Reopening.

We need to investigate and figure out what's going on. @lukos, we'll use your site 'loginoictest' for investigations. Could you share the UTC timestamp of one such occurrence of the error on that site?

**Comment by lukos** [comment] 2016-09-29 19:15
15:37 UTC today (29th Sept).

**Comment by barranger** [comment] 2016-09-29 19:21
Not to pile on but having the same problem here

**Comment by davidebbo** [comment] 2016-09-29 19:29
Ok, clearly there is some kind of issue. Basically, it looks like the payload we receive from the VSTS receive hook might have something bad in it.

As a test, can you try setting `SCM_USE_LIBGIT2SHARP_REPOSITORY=0` in the Azure App Settings for that site? It won't solve it, but the error might be clearer (using git instead of libgit2sharp).

**Comment by davidebbo** [comment] 2016-09-29 19:33
Actually, one more App Setting to add: `SCM_TRACE_LEVEL=4`.

**Comment by lukos** [comment] 2016-09-29 19:41
fatal: Authentication failed for 'https://peddc2lebmehbm3btu7fk4oiephwq4p4zfjixjrz22tm3eqcsoxq:@SNIP.visualstudio.com/_git/COM.SNIP.SNIP/'\n\r\nD:\Program Files (x86)\Git\cmd\git.exe fetch origin --progress

**Comment by suwatch** [comment] 2016-09-29 20:22
As far as the payload goes, all seems fine.   We have contacted the VSTS team why the token is not valid.   Will update.

**Comment by davidebbo** [comment] 2016-09-30 02:35
The VSTS team is investigating and making progress. We'll update the thread tomorrow.

**Comment by svpsiva** [comment] 2016-09-30 04:04
Facing the same issue with my Azure app service and VSTS code repository.

**Comment by davidebbo** [comment] 2016-09-30 17:07
Update: the VSTS team is aiming to deploy a fix later today.

**Comment by suwatch** [comment] 2016-09-30 23:43
VSTS team has rolled out the fix.  @lukos mind trying if still issue?

**Comment by svpsiva** [comment] 2016-10-01 07:32
Worked for me. Deployment is successful. 
Thanks.

**Comment by davidebbo** [comment] 2016-10-01 19:15
@svpsiva thanks for confirming. Closing the issue.

**Closed by davidebbo** 2016-10-01 19:15 UTC
