### ISSUE TITLE
Missing url and output_url in webhook callbacks for scheduled jobs.

### ISSUE THREAD

**Issue by JZ-Dentos** [projectkudu/kudu#2120] opened 2016-08-30 06:55 UTC
When a job is manually triggered from the WebJob UI in Azure, the webhook callback message body contains 'url' and 'output_url' fields. If the job is triggered on a schedule, those fields are missing.

**Comment by davidebbo** [comment] 2016-08-31 00:48
When you say 'running on a schedule', are you referring to:

1. Hooked up to the Azure Scheduler
2. Using Kudu's CRON support

See [doc](https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/#CreateScheduledCRON) for a description of both techniques.

**Comment by JZ-Dentos** [comment] 2016-08-31 17:14
The CRON.

**Comment by davidebbo** [comment] 2016-08-31 22:52
To make sure there is no misunderstanding, can you clarify what you mean by "webhook callback message"? Can you paste an example of the body you get in both cases?

**Comment by JZ-Dentos** [comment] 2016-09-05 05:59
By webhook callback message, I mean the JSON object that is passed as the message body in the HTTP request made to a webhook upon job completion. (I.e. the hook is installed as a 'TriggeredJobFinished' hook via <appname>.scm.azurewebsites.net/api/hooks). 

It seems that the missing url fields might be related only to the case of a scheduled job failing. Below are two examples from the same webjob (I've omitted the actual names of the job and the app):

{
 "id": "201609050530002030",
 "name": "201609050530002030",
 "status": "Success",
 "start_time": "2016-09-05T05:30:00.2030442Z",
 "end_time": "2016-09-05T05:38:37.2387069Z",
 "duration": "00:08:37.0356627",
 "output_url": "https://XXXXXX.scm.azurewebsites.net/vfs/data/jobs/triggered/YYYYYY/201609050530002030/output_log.txt",
 "url": "https://XXXXXX.scm.azurewebsites.net/api/triggeredwebjobs/YYYYYY/history/201609050530002030",
 "job_name": "YYYYYY",
 "trigger": "Schedule - 0 30 * * * *"
}

{
 "id": "201608291930003421",
 "name": "201608291930003421",
 "status": "Failed",
 "start_time": "2016-08-29T19:30:00.3421046Z",
 "end_time": "2016-08-29T19:32:23.1639725Z",
 "duration": "00:02:22.8218679",
 "job_name": "YYYYYY",
 "trigger": "Schedule - 0 30 * * * *"
}

**Comment by davidebbo** [comment] 2016-09-06 02:51
I see. When I tested the other day with a scheduled job, it was working fine, but my job was not failing. Could it be that the issue is in fact unrelated to whether the job is manually triggered or scheduled, but is instead a general issue with failing jobs? If so, let's update the issue title accordingly.

**Comment by davidebbo** [comment] 2016-09-06 03:02
Well, I played with it some more and I can't repro. My test WebJob is very simple. `settings.job` has:

```
{
    "schedule": "0 * * * * *"
}
```

And `run.cmd` has:

```
@echo Hello
exit /b 1
```

I then set up a webhook and point it to a Request Bin (http://requestb.in/). When it triggers, the two fields are there.

Can you test with my exact steps to see if that repros for you? If not, we'll need to identify what's different with yours.

**Comment by davidebbo** [comment] 2016-09-13 00:49
Closing, but happy to reopen if we get to the point that we can repro what you observe.

**Closed by davidebbo** 2016-09-13 00:49 UTC

**Comment by JZ-Dentos** [comment] 2016-09-19 10:20
I've seen the issue now with a successful job as well. I haven't been able to reproduce with manually triggered jobs, nor does it happen every time with a scheduled job.

**Comment by davidebbo** [comment] 2016-09-19 14:58
Do you mean you saw this with the steps I gave above (if not do try to help isolate)? What was the frequency of cases that were missing the fields?

**Comment by JZ-Dentos** [comment] 2016-09-20 06:20
I haven't had time to try out those specific steps, as I've implemented a workaround for it in the component receiving the webhook request. I tend to see the issue with a job I'm running regularly. I doubt that the job itself would make any difference, unless somehow the output log is involved? 
I can't say what the frequency of the occurrence is. It doesn't seem to be random though. Rather, the problem occurs repeatedly and then sometimes it doesn't appear at all.
If you happen to know where in the code the request is generated, I could take a look at the code to see if I spot any problems.

**Comment by davidebbo** [comment] 2016-09-20 14:54
Relevant code is [here](https://github.com/projectkudu/kudu/blob/c79640699186600004277a87584bbd7138d70b64/Kudu.Core/Jobs/TriggeredJobsManager.cs#L207-L223).

It has:

    OutputUrl = BuildVfsLogUrl(triggeredJobRunPath, jobName, runId, TriggeredJobRunLogger.OutputLogFileName)

And `BuildVfsLogUrl` can return null in some cases, which would indeed cause the missing property. Specifically, it returns null when `output_log.txt` is missing under `
D:\home\data\jobs\triggered\YourJobName\201609190459005451`.

When you hit this condition, can you check whether that file is missing for that particular run?
