### ISSUE TITLE
Web App service not restarting after zip deploy, previous site package serving requests/Loaded into memory

### ISSUE THREAD

**Issue by jstallm** [projectkudu/kudu#2952] opened 2019-03-20 21:46 UTC
I noticed today that upon successfully deploying my application from an Azure Devops release pipeline that after deployment, the previous artifact was serving responses to requests vs the latest deployed artifact UNTIL I restarted the application. This was very strange since I was under the impression that previous assemblies were unloaded after a deployment to an app service. 

### Repro steps.

Here were steps for me to produce;
Deploy app service using Azure Devops App Service Deploy task. Create a rest api endpoint on the application which simply returns the assembly version using a setter equal to 

`typeof(Program).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion`
as a string.
Even if the two artifacts have completely different versions, the assembly that is loaded into memory appears to still be version of application that was previously overridden during the deployment. Run a restart on the application using azure portal. Re-run a request to the endpoint that returns the assembly version and this time it will have the latest deployed version. 

How is it that after a deployment the previous assembly is still loaded into memory such that a request to the app service returns a response from the application artifact that was JUST overriden with a new version? Why does restarting load the latest deployed artifact but not a deployment task in azure devops?

@suwatch  could this be a bug from commit 8c8eba7?

This odd issue happened on both an api app and web app. Also happened on free and paid plan.

**Comment by jstallm** [comment] 2019-03-21 18:18
Still seeing this happen today. I even tried the following to ensure I wasnt crazy. 
I deployed an application, with dll versioned to 1.0.0-beta.1+0
Then, I deploying a different release, versioned as 1.0.0-beta.1+1. 
Using App Service > Advanced Tools (Kudo) I downloaded the dll and using ildasm.exe checked the version and it was 1.0.0-beta.1+0.
I restarted the application and downloaded the dll again, opened in the dll using ildasm.exe checked the version and it was 1.0.0-beta.1+1. 

Why does restart change the file? Why isnt deploy restarting the application itself? 

This is really very unexpected and makes deployments fail essentially, since Id imagine many engineers are necessarily creating restart tasks after every deployment explicitly.

**Comment by suwatch** [comment] 2019-03-22 00:16
The `Invalid access to memory location` could be because you have WEBSITE_RUN_FROM_ZIP or WEBSITE_RUN_FROM_PACKAGE set to 1 or url.   This is benign error since, in this mode, one cannot modify the file (nor touch its datetime).

As for change did not take effect (has nothing to do.   We will need a site name and UTC time of the deployment and we can help investigate why.

**Comment by jstallm** [comment] 2019-03-22 00:20
It would be strange to me if nobody else is having this issue since it has appeared to be systemic as it is happening to multiple web apps I have. I dont think this is idiosyncratic to me.

**Comment by jstallm** [comment] 2019-03-22 00:23
Is their any explanation as to why the previous dll was loaded into memory and only until I restarted the app did the new dll replace the old? This is super strange behavior, and very confusing.

**Comment by suwatch** [comment] 2019-03-22 00:52
If you provide a sitename and UTC time of deployment having issue, we like to look at the log to see what was going on and fix it.

**Comment by jstallm** [comment] 2019-03-22 01:05
sitename: https://binaryloadingissue-jws.azurewebsites.net/

logs of azure devops release deploying:
`2019-03-22T01:02:52.5758815Z ##[section]Starting: Deploy Azure App Service
2019-03-22T01:02:52.5874844Z ==============================================================================
2019-03-22T01:02:52.5875190Z Task         : Azure App Service Deploy
2019-03-22T01:02:52.5875367Z Description  : Update Azure App Services on Windows, Web App on Linux with built-in images or Docker containers, ASP.NET, .NET Core, PHP, Python or Node.js based Web applications, Function Apps on Windows or Linux with Docker Containers, Mobile Apps, API applications, Web Jobs using Web Deploy / Kudu REST APIs
2019-03-22T01:02:52.5875533Z Version      : 4.3.21
2019-03-22T01:02:52.5875625Z Author       : Microsoft Corporation
2019-03-22T01:02:52.5875781Z Help         : [More information](https://aka.ms/azurermwebdeployreadme)
2019-03-22T01:02:52.5875932Z ==============================================================================
2019-03-22T01:02:53.6488025Z Got service connection details for Azure App Service:'BinaryLoadingIssue-jws'
2019-03-22T01:02:54.5347695Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"1"}
2019-03-22T01:02:55.2718123Z Updated App Service Application settings and Kudu Application settings.
2019-03-22T01:02:55.5846751Z Package deployment using ZIP Deploy initiated.
2019-03-22T01:02:57.1736856Z Successfully deployed web package to App Service.
2019-03-22T01:02:58.2294350Z App Service Application URL: http://binaryloadingissue-jws.azurewebsites.net
2019-03-22T01:02:58.2533008Z ##[section]Finishing: Deploy Azure App Service`

The logs above deployed version '1.4.0-alpha.14', but despite this, the previously deployed version '1.4.0-alpha.11' is still running/loaded into memory.

**Comment by jstallm** [comment] 2019-03-22 01:07
At what point does the azure app service unload the previously deployed site package and load the newly pushed Site Package? I assumed it was upon deployment but this issue invalidates that assumption

**Comment by suwatch** [comment] 2019-03-22 06:12
The whole idea was after deployment, site will restart to pick up change automatically (within 5-10s).   User need not do any extra work.   We will look into the log and update.   I notice you are using FREE plan - I wonder if that might be some limitation of such.   Do you have a paid plan that you can try to repro this?

**Comment by DavidZidar** [comment] 2019-03-22 14:56
I'm not on a free plan and I'm experiencing the same or a similar issue. The zip deployment seemingly succeeds and the `packagename.txt` file is updated correctly but the site never restarts so the old deployment is still active many minutes later, until the site is manually restarted it seems.

My deployment logs say nothing of any invalid accesses to memory though.

**Comment by jstallm** [comment] 2019-03-22 17:18
@suwatch , I initially noticed the issue on both the free plan **and** paid plan. After, I created the website above using free plan in order to reproduce.

**Comment by jstallm** [comment] 2019-03-22 17:36
@suwatch , if restart is guaranteed as you mention above, you should the be able to see a restart perhaps within some internal logs you have available shortly after 2019-03-22T01:02:57.1736856Z. But you wont see that the app restarted, since if it did I wouldnt have seen the issue. Can you please confirm that the logs do not have restarts? What code is responsible for the restart?

**Comment by jstallm** [comment] 2019-03-22 18:13
I also see that restart is not guaranteed necessarily and that its based on 
https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts

I see
`await this.kuduServiceUtility.deployUsingZipDeploy(webPackage, this.taskParams.TakeAppOfflineFlag, 
            { slotName: this.appService.getSlot() });`

whichs indicates to be that the only value that determines whether or not to restart the app is this argument. 
Did the default value for this change recently to false?

fyi, within my azure devops jobs I have Select Deployment Method unchecked. This has remain unchecked and I have never changed this setting.

**Comment by jstallm** [comment] 2019-03-22 18:18
Interesting, I see its set the false by default. I now wonder how in the world the restart was initiated in the past? 
`TakeAppOfflineFlag: tl.getBoolInput('TakeAppOfflineFlag', false),`
https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/operations/TaskParameters.ts#L123

**Comment by suwatch** [comment] 2019-03-22 18:36
@thaishankar  please assist.

**Comment by jstallm** [comment] 2019-03-22 21:50
K, I have resolved this by being explicit about the 'deployment method' within the stages task. 

Its not necessarily evident to someone who is creating/configuring the 'Azure App Service Deploy' task that the implied/auto-detect will **not** necessarily restart the application. 

Configuration shown below for my resolution. 
![image](https://user-images.githubusercontent.com/6054668/54854940-c6d0b600-4cb1-11e9-8132-1cdf2883701a.png)

**Comment by DavidZidar** [comment] 2019-03-22 22:14
Previously sites were always automatically restarted when ZIP deploy was performed even if no settings had been changed. My deployment issues started yesterday.

For now I have worked around the issue by sending `DELETE /api/processes/-1` to terminate the main process if the site does not start serving the expected version within a specified amount of time.

**Comment by suwatch** [comment] 2019-03-22 22:37
We are still looking .. thanks for reporting

**Comment by suwatch** [comment] 2019-03-23 00:08
We figured out the issue.   Our latest upgrade caused this regression.   If your Azure App Service version is 81 and higher, you are affected.   We are working on the hot fix which will roll out next week.   Apology for the inconvenience.  The work around is to restart the site.   We understand it wasn't the best workaround but, at minimum, should get you unblocked.

**Comment by jstallm** [comment] 2019-03-23 00:18
@suwatch , where is the best place to track the progress of this ? This issue? Another? thank you.

**Comment by suwatch** [comment] 2019-03-23 00:24
I will personally update this once the fix goes out.   If you have sites that would want to get the fix early (please share you site name here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)).    The earliest time for the fix is next Mon (3/25) and may take a few days after.

**Comment by pharring** [comment] 2019-03-23 23:24
@suwatch thanks for the update. I bumped into this myself yesterday. I thought the error was on my end (did the deployment silently fail?) and I spent some time going over our Azure DevOps deployment tasks looking for the error.

**Comment by danzel** [comment] 2019-03-26 02:05
This sounds like what we are running in to.

Watching the logs while the deploy happens, we see this:
```
2019-03-26T01:55:14  Fetching changes.
2019-03-26T01:55:14  Updating submodules.
2019-03-26T01:55:14  Preparing deployment for commit id '5bbf85541b'.
2019-03-26T01:55:14  Skipping build. Project type: Run-From-Zip
2019-03-26T01:55:14  Skipping post build. Project type: Run-From-Zip
2019-03-26T01:55:15            Error occurred, type: error, text: Invalid access to memory location., stackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)at Kudu.Core.Deployment.DeploymentManager.TryTouchWatchedFile(DeploymentContext context, DeploymentInfoBase deploymentInfo) in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\DeploymentManager.cs:line 858
2019-03-26T01:55:15  Updating D:\home\data\SitePackages\packagename.txt with deployment 20190326015514.zip
2019-03-26T01:55:15  Deployment successful.
```

After that, the app never gets reloaded for the new version and we continue running the old version.

**Comment by jstallm** [comment] 2019-03-26 18:02
@danzel , yeah you are having exact same issue.

**Comment by jstallm** [comment] 2019-03-26 18:03
@suwatch , any updates?

**Comment by jstallm** [comment] 2019-03-26 18:04
@suwatch , I accidentally closed this issue while trying to post. please advise.

**Comment by suwatch** [comment] 2019-03-26 22:26
The fix has been rolled out to 90% of the scale units ..  please verify and let us know if still not fix and provide us the [sitename](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

**Comment by suwatch** [comment] 2019-03-27 03:08
The issue should be mitigated now.  Thanks for reporting, apology for the inconvenience.

**Closed by suwatch** 2019-03-27 03:08 UTC

**Comment by blueelvis** [comment] 2020-03-11 12:47
@suwatch - I am also facing this issue across our various environments for multiple web apps which are using the Zip Deploy method. The only way is to stop the web app, wait for it to give 403 and then start it again. We do have a support ticket (**120011524002498**) going on but it has been quite some time.

Web App name -- aze...-d-web-02-webapp

**Comment by suwatch** [comment] 2020-03-15 00:43
Umm .. that was over a year ago.  Please provide UTC time of your deployment and we can look into it.

**Comment by blueelvis** [comment] 2020-03-15 17:33
@suwatch - I know :( . If you want, I can create a new Github issue. Here is the UTC timestamp -- 11:21 AM on Wed Mar 11 2020.

**Comment by suwatch** [comment] 2020-03-15 18:27
Yes please create a new one .. put as many such as time of inicident, partial site and subscription name.

**Comment by robert-skarzycki** [comment] 2020-04-30 13:28
@suwatch , what exact Kudu version is a fixed one? In my case `85.11226.4297` seems to be buggy (I was acing similar problem in April), but on freshly created app plan & app service (with `86.20224.4450`) I can't reproduce that. If the latter version is fine, how to update that? Is it possible without recreation of app plan / app service?

**Comment by suwatch** [comment] 2020-04-30 16:44
restart the webapp should pick up the latest Kudu automatically.  If not, check `d:\home\siteextensions\kudu` and see if exists (it will override the Kudu available on VM).   If still not, [share your site name](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

**Comment by Stephen-McDowell** [comment] 2020-04-30 22:38
We're being bit by the 'Invalid access to memory location.' issue.  We are deploying to a slot.  Taking some tips from the comments from last year I did the following to get the deployments working again:  1) enabled 'Select deployment method' 2) selected 'Zip Deploy' as the Deployment method and 3) enabled 'Take App Offline'.  Interested in getting this sorted out.  
Subscription ID: 89b....1f85
Site: ...account-scus/staging

**Comment by robert-skarzycki** [comment] 2020-05-04 17:01
@suwatch:
```
Subscription: 2e17...66fb
Site: sq-sto...od
```

**Comment by suwatch** [comment] 2020-05-04 22:32
@robert-skarzycki   did you restart (stop and start) the site?   this is to force the pickup of new Kudu.

**Comment by robert-skarzycki** [comment] 2020-05-05 17:08
@suwatch, in fact start & stop helped with getting latest Kudu. During upcoming deployment I'll check if this will help, but I guess it should. Thanks! :)

**Comment by sofiaxtdev** [comment] 2023-01-23 05:41
I started to experience this issue this january. 
I had to restart web app manually to see the changes done.

**Comment by bcspragu** [comment] 2023-06-28 23:03
Piggybacking on a multi-year old closed bug to note that I see this behavior with a containerized app and GitHub Actions deployment.

My CI pipeline looks something like:

```yaml
      - name: Deploy <the app> on Apps Service
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          app-name: <name of the app>
          images: <registry>.azurecr.io/<app>:dev
```

It runs successfully, and I see in Kudu that it was successful as well, but the behavior is clearly that of the old version, and it isn't until I hit "Restart" in the Azure portal that the new version starts being served.

**Comment by erikrok** [comment] 2023-08-15 11:01
Experiencing the similar issue through zipapp deployment from az cli
`az webapp deployment source config-zip`.

I am required to make a restart of the webapp after a successful deployment otherwise it runs on "old"/cached version.

**Comment by jstallm** [comment] 2023-08-15 12:41
Yes restart > Experiencing the similar issue through zipapp deployment from az cli
> 
> `az webapp deployment source config-zip`.
> 
> 
> 
> I am required to make a restart of the webapp after a successful deployment otherwise it runs on "old"/cached version.

**Comment by MakakWasTaken** [comment] 2023-09-01 08:06
I have also recently started experiencing this bug. While manually stoping/starting the web app service gets the newest deployment, it doesn't fix the issue. It is a bit annoying that a manual restart is required every time new changes are deployed.

**Comment by wolfpaulus** [comment] 2024-01-18 05:37
Azure is for children .. let's go where all the gown up are.
I'm out of here.
