### ISSUE TITLE
Deploy from Gitlab fails with 'Host key verification failed'

### ISSUE THREAD

**Issue by leedjones** [projectkudu/kudu#2279] opened 2016-12-20 13:54 UTC
I am attempting to deploy to an Azure app service from Gitlab (https://christianliebel.com/2016/05/auto-deploying-to-azure-app-services-from-gitlab/) but ran into a problem. The deployment fails

`Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\r\nD:\Program Files (x86)\Git\cmd\git.exe fetch origin --progress`

I've deleted the deployment configuration in the App service a few times and recreated to make sure the SSL URL for the Gitlab repository is correct. I've also tried adding my key into the Gitlab deployment keys but it wont let me as its already there, so I know the key is definitely correct.

Searching around on the web suggests to remove the host from the known hosts file, but as this is on azure there is no known_hosts in the /ssh folder (Kudu->Console->D:\home\.ssh) so I'm not sure what else to try.
I've followed this guide on other Azure websites and never had a problem, its just on this one thats causing the issue.

Thanks

**Comment by watashiSHUN** [comment] 2016-12-23 06:29
can you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? I'll take a look at what's going on.

**Comment by h4ng4r18** [comment] 2017-01-05 14:42
I am experiencing the same thing

I have created a dummy appservice called **dummy369duf** the appservice in question reads **d******b**

**Comment by davidebbo** [comment] 2017-01-05 15:39
Back to original post, the known_hosts file is in `D:\home\.ssh`. Try going to that folder from Kudu Console and run `ssh gitlab.com` to test the connection.

**Comment by h4ng4r18** [comment] 2017-01-05 15:44
Just given that a shot...

_D:\home\.ssh>ssh gitlab.com
Pseudo-terminal will not be allocated because stdin is not a terminal.
Host key verification failed._

**Comment by davidebbo** [comment] 2017-01-05 15:50
Correction, the command to try is `ssh -T git@gitlab.com`.

When trying that after setting up my deploy key in GitLab, I get this:

```
D:\home\.ssh>ssh -T git@gitlab.com
Welcome to GitLab, Anonymous!
```

**Comment by h4ng4r18** [comment] 2017-01-05 15:56
Okay, mine fails

_D:\home\.ssh>ssh -T git@gitlab.com
Host key verification failed._

**Comment by davidebbo** [comment] 2017-01-05 16:00
Are you sure that you followed the step where you go to https://[yourapp].scm.azurewebsites.net/api/sshkey?ensurePublicKey=1 to get the public key from Kudu? After doing this you should see several files in `d:\home\.ssh`: config, id_rsa, id_rsa.pub. Do you have those?

**Comment by h4ng4r18** [comment] 2017-01-05 16:10
I have put public key from above URL pattern into Deploy Keys in private Gitlab project several times under different names (deleting before re-adding)...

Having done this again now, I can confirm that those files now exist

_D:\home\.ssh>ls
config
id_rsa
id_rsa.pub

D:\home\.ssh>ssh -T git@gitlab.com
Warning: Permanently added 'gitlab.com,104.210.2.228' (ECDSA) to the list of known hosts.
Welcome to GitLab, Anonymous!_

Fetch still fails with OP's
_Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\r\nD:\Program Files (x86)\Git\cmd\git.exe fetch origin --progress_

**Comment by davidebbo** [comment] 2017-01-05 16:15
Does it work if you manually clone your repo from Kudu Console? e.g.

    git clone git@gitlab.com:yourname/yourrepo.git

**Comment by h4ng4r18** [comment] 2017-01-05 16:20
I can clone and the files were imported successfully

Fetch from within Deployment Details panel still fails after re-creation

**Comment by davidebbo** [comment] 2017-01-05 17:39
I just tried and it worked fine for me. Make sure you use the ssh url when you set up the external repo, and not the https url! Could that be the problem for you?

**Comment by h4ng4r18** [comment] 2017-01-05 17:43
I've been using the SSH URL
_git@gitlab.com:myusername/myreponame.git_

**Comment by davidebbo** [comment] 2017-01-05 18:01
Can you try setting `SCM_USE_LIBGIT2SHARP_REPOSITORY=0` in the Azure App Settings? This is to make sure it doesn't use libgit2sharp, which doesn't support ssh. Though it did work fine for me without that...

Also, can you clarify what's not working for you? Is it:

1. Clicking the Sync button in Azure Portal OR
2. Automatic deployment via webhook?

**Comment by davidebbo** [comment] 2017-01-05 18:03
Actually, ignore the `SCM_USE_LIBGIT2SHARP_REPOSITORY` suggestion, as I see from your log that it's correctly falling back to git,exe.

**Comment by davidebbo** [comment] 2017-01-05 18:08
Look at your webapp (d******b), I see no files at all in your `D:\home\.ssh` folder. Are you sure this is the right app?

**Comment by h4ng4r18** [comment] 2017-01-07 00:19
Lost as to why this is now working, but here's the winning sequence

Generated another key from /api/sshkey?ensurePublicKey=1

Set the ssh-rsa key for deployment in gitlab with a new name and then confirmed ssh successfully returns the welcome message from the PS console

Revisited the App Deployment > Deployment Options panel, did a Redeploy followed by a sync and we're off

Thanks David

**Comment by davidebbo** [comment] 2017-01-07 01:33
Weird. Closing for now. If you find a sequence of steps that should work and doesn't we can reopen and discuss further.

**Closed by davidebbo** 2017-01-07 01:33 UTC

**Comment by hatdropper1977** [comment] 2018-01-08 22:41
I had this problem with an Ansible playbook.  I fixed it by shelling into the target server and then running the following command:

```bash
[centos@ip-10-0-0-25 ~]$ ssh git@github.com
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
RSA key fingerprint is MD5:16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
PTY allocation request failed on channel 0
Hi hatdropper1977! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```
Then, when I ran the playbook it worked.

I then integrated the known_hosts file into my playbook - to remove the manual step of needing to ssh to github in order to get the fingerprint.

```bash
github.com,192.30.253.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
```

**Comment by gato-negro** [comment] 2018-02-20 17:29
Same thing here. Was that ever resolved?

**Comment by Jaffacakes82** [comment] 2018-05-01 19:55
Same problem as OP. For some reason Kudu had deleted my SSH key pair. Regenerating and reapplying to GitLab worked.

**Comment by maxwell-k** [comment] 2018-05-30 13:30
If I understand correctly 

1. `az webapp deployment source delete` will remove  `D:\home\.ssh`. 
2. Then I add a deployment back again.
3. The first time I visit `https://[yourapp].scm.azurewebsites.net/api/sshkey?ensurePublicKey=1`  I get a key returned in the browser but `D:\home\.ssh` doesn't exist yet.
4. The second time I visit the URL `D:\home\.ssh` appears with the expected files.

I could probably script this if reliably reproducing the issue would help you with a fix @davidebbo ?

**Comment by davidebbo** [comment] 2018-05-31 14:50
@maxwell-k I can't explain that. in my tests, if I delete the .ssh folder and then got to that URL, it gets recreated on the first try.

**Comment by frankchen76** [comment] 2018-08-21 21:19
I want to follow up this thread. I am currently working on a Azure Function and try to use the same approach to get source code from GitLab. The really weird thing is when I run api/sshkey?ensurePublicKey=1, I can find out .ssh folder was created under d:\home folder from Kudu console. however, just a few seconds later, when I did a "dir", the .ssh folder was gone. I am just wondering if it's associated with the Azure Function which I created by using "Consumer plan". it means my environment might be a random vm initialized for my Azure Function. can same approach apply to Azure Function with "Consumer Plan"?

**Comment by davidebbo** [comment] 2018-08-21 21:24
@frankchen76 that is not expected, and I am not able to repro this in a Function app running in Consumption plan. The .ssh folder gets created with 3 files in it, and they persist.

**Comment by Krackone** [comment] 2019-06-02 13:35
I'm not sure if this is an option for you, but I disconnected the project from the Web App in the Deployment settings and reconnected it and that seemed to work for me. I was having the same issue.

**Comment by marchy** [comment] 2019-06-18 21:07
This keeps happening to us on different instances.
On the instances where it has started to happen, disconnecting and reconnecting doesn't fix it either.

Any recent changes that might have impacted the Git connections in Deployment Center?

**Comment by Sevastyan** [comment] 2019-12-17 15:49
The following helped me in a similar situation:

```
ssh-keyscan -t ed25519 <address_of_your_gitlab_instance> >> ~/.ssh/known_hosts
```

**Comment by RobbiNespu** [comment] 2021-09-27 05:10
> 
> 
> The following helped me in a similar situation:
> 
> ```
> ssh-keyscan -t ed25519 <address_of_your_gitlab_instance> >> ~/.ssh/known_hosts
> ```

Thanks! your hack worked for me
