### ISSUE TITLE
logstream is extremely slow to load

### ISSUE THREAD

**Issue by hcapp01** [projectkudu/kudu#2081] opened 2016-07-13 00:47 UTC
It take forever to load https://{name}.scm.azurewebsites.net/logstream

**Comment by ahmelsayed** [comment] 2016-07-13 00:49
Which browser are you using? The problem is that some browsers will buffer the response because of the `"text/plain"` mime type

**Comment by hcapp01** [comment] 2016-07-13 03:37
Mac chrome and safari both take several minutes to load. Shall I try windows IE?

**Comment by davidebbo** [comment] 2016-10-24 23:41
Closing since this is really a browser issue. If you use `curl`, it works with no delays.

**Closed by davidebbo** 2016-10-24 23:41 UTC

**Comment by ritazh** [comment] 2016-10-25 00:01
For others who might run into this issue in the future, try the Log Stream UI in Azure portal. It’s so much faster!!! Thanks @davidebbo! 👍

**Comment by luismesagravedeperalta** [comment] 2018-02-16 11:40
@davidebbo It's an issue in ALL browsers... doesn't it make it an issue for kudu indeed?? I've NEVER been able to acually see this console. I used to go to Azure UI as @ritazh suggests, but now I don't have access to it and I really need the kudu console, and it doesn't work. It's been like that for years now. Could you please kindly take a look at it and make it work?
Best
PS: my console hasn't loaded yet... still waiting..

**Comment by davidebbo** [comment] 2018-02-16 19:01
@luismesagravedeperalta Please just use `curl` instead as explained above. We should probably just remove that option from the Kudu menu.
