### ISSUE TITLE
Kudu doesn't honor DNX version

### ISSUE THREAD

**Issue by bitcrazed** [projectkudu/kudu#1663] opened 2015-08-18 22:13 UTC
In [/common/Constants.cs #54](https://github.com/projectkudu/kudu/blob/012114c74bc310d9daa36a2c2d6240c3e30b482e/Common/Constants.cs#L54), Kudu currently sets `DnxDefaultVersion` to "1.0.0-beta5" and uses this setting when deploying my ASP.NET 5 Beta 6 app:

> Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspNet5 "D:\home\site\repository\src\buggr.web\project.json" --aspNet5Version "1.0.0-beta5" --aspNet5Runtime "CLR" --aspNet5Architecture "x86"'.
Project file path: .\src\buggr.web\project.json
Generating deployment script for ASP.NET 5 Application

Questions:

1. Should this not be updated to Beta6 now that Beta6 is released (and kept in-sync with new versions as released)?
2. Could the [ASP.NET 5 SDK deployment helper](https://github.com/projectkudu/kudu/blob/fab678a2e4abac7d194bb5799479a5b2eb953b65/Kudu.Contracts/Deployment/AspNet5Sdk.cs) gather the required version of DNX from the deployed app's global.Jason file:
```
{
  "sdk": {
    "version": "1.0.0-beta6"
  }
}
```
Or am I missing something? ;)

**Comment by ahmelsayed** [comment] 2015-08-18 22:36
That constant is only used if we fail to determine the version from `global.json`. That being said, we should update the constant to beta6.

Do you have a `global.json` that kudu isn't using?

**Comment by ahmelsayed** [comment] 2015-08-18 22:54
FYI - I just updated the constant in b31e6aee952cf983c813ebb6e131adfb0e886c01

**Comment by bitcrazed** [comment] 2015-08-19 17:36
@ahmelsayed Yes, I do have a global.json, the contents of which are the blob of JSON above.

**Comment by ahmelsayed** [comment] 2015-08-19 17:45
I can't reproduce this. Here is a test repo that works as expected https://github.com/ahmelsayed-test/HelloWeb as you can see [`global.json`](https://github.com/ahmelsayed-test/HelloWeb/blob/master/global.json) it's the same as yours and kudu installs beta6 correctly.
Do you mind sharing a repo that reproduces the issue you're seeing?

**Comment by davidebbo** [comment] 2015-08-19 19:01
@bitcrazed Please see https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue

**Comment by bitcrazed** [comment] 2015-08-19 20:31
@davidebbo Completely agree - will share my repro as a GitHub repo. Working on it as I type.

**Comment by bitcrazed** [comment] 2015-08-19 20:33
@davidebbo @ahmelsayed Can I run the step that generates the Azure deployment script locally, without needing to deploy Azure via GitHub?

**Comment by ahmelsayed** [comment] 2015-08-19 20:51
You don't have to deploy to azure via github to repro this. You can just git push from your local repo
```
git push https://<YourSiteName>.scm.azurewebsites.net master
```

Unfortunately, you can repro this locally because the tool that generates the script asks for the dnx version in the parameters. Normally you would run it like this

```
npm install -g kuduscript
kuduscript -y --no-dot-deployment -o <outputFolder> --aspNet5 <path to project.json> --aspNet5Version <Dnx version> --aspNet5Runtime <CLR or CoreCLR> --aspNet5Architecture <x86/x64>
```
So as you can see it asks for the `<Dnx version>` on the command line. Kudu is the one that is supposed to supply that to the tool that generates the script.

**Comment by bitcrazed** [comment] 2015-08-19 21:10
Okay, can't share offending repo (originally created using Yeoman ```yo aspnet```) so I created a new project to get a baseline:

Created a new project via VS 2015 File | New Project | Web - ASP.NET Web Application -> ASP.NET 5 app. Modified nothing within the project and built it. Ran locally to test app was well. A-OK.

Created a local Git repo & remote GitHub repo. Pushed project to repo: https://github.com/bitcrazed/HelloWebApp

Created Azure Web App (using new Azure portal) & configured CI via GitHub.

Waited until deployment complete, then browsed to site (http://bitcrazed-HelloWebApp.azurewebsites.net) and all looks good.

Checked deployment script - was as expected (noting expected version of ASP.NET 5):

> Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspNet5 "D:\home\site\repository\src\HelloWebApp\project.json" --aspNet5Version "***1.0.0-beta6***" --aspNet5Runtime "CLR" --aspNet5Architecture "x86"'.
Project file path: .\src\HelloWebApp\project.json
> Generating deployment script for ASP.NET 5 Application

Then I removed global.json from filesystem and solution, and pushed the updated project to GitHub. 

Once deployment complete, confirmed that the current Kudu engine is assuming Beta5 (see thread above) which @ahmelsayed has already fixed (I guess awaiting deployment).

> Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspNet5 "D:\home\site\repository\src\HelloWebApp\project.json" --aspNet5Version "1.0.0-***beta5***" --aspNet5Runtime "CLR" --aspNet5Architecture "x86"'.
Project file path: .\src\HelloWebApp\project.json
> Generating deployment script for ASP.NET 5 Application

### So, what's different between my offending solution and this one?
It appears that the offending solution has a global.json file in the web app project root (I.e. .../src/project_name/global.json), rather than in the solution root (I.e. .../). Does Kudu assume that global.json is in the solution root or does it lookup the file's location as specified in the solution file?

**Comment by bitcrazed** [comment] 2015-08-19 21:13
@ahmelsayed Thanks for the info re. deployment. In my steps above, I created a GitHub repo so you guys could see what I'd done and so that I could repro the environment I see in my offending app.

Re. Script gen':
Was wondering if I could kick Kudu locally to generate the output script - this way I could repro & debug locally. No problem if not - the environment works for now ;)

**Comment by ahmelsayed** [comment] 2015-08-19 21:17
I see. Yes we assume that [global.json will be in the solution root](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/AspNet5Helper.cs#L56), at least that's how I thought project layout is supposed to be. I'll try yoman and see what layout it generates.

About debugging locally, you can run kudu locally and then you'll be able to debug this part locally. you can take a look at our [Getting Started](https://github.com/projectkudu/kudu/wiki/Getting-started) wiki for that

**Comment by bitcrazed** [comment] 2015-08-19 21:23
Thanks - will take a look at running Kudu locally - it's a :top: tool :grinning: 

When creating a project via Yeoman, no global.json is created, nor any VS solution / project files since ASP.NET 5 is aiming to support non-MS platforms. Here's the list of files created using the current template:

```
create test\gulpfile.js
create test\.bowerrc
create test\.gitignore
create test\bower.json
create test\config.json
create test\hosting.ini
create test\package.json
create test\project.json
create test\README.md
create test\Startup.cs
create test\Controllers\HomeController.cs
create test\Views\_ViewImports.cshtml
create test\Views\_ViewStart.cshtml
create test\Views\Home\About.cshtml
create test\Views\Home\Contact.cshtml
create test\Views\Home\Index.cshtml
create test\Views\Shared\_Layout.cshtml
create test\Views\Shared\Error.cshtml
create test\wwwroot\css\site.css
create test\wwwroot\favicon.ico
create test\wwwroot\images\ASP-NET-Banners-01.png
create test\wwwroot\images\ASP-NET-Banners-02.png
create test\wwwroot\images\Banner-01-Azure.png
create test\wwwroot\images\Banner-02-VS.png
create test\wwwroot\js\site.js
```

**Comment by bitcrazed** [comment] 2015-08-19 21:29
Looks like my offending project had global.json added to the wrong location - will move for now, but it might be worth adjusting Kudu to look for the global.json location as specified in the solution file.

**Comment by ahmelsayed** [comment] 2015-08-19 21:34
As far as I know global.json should be in the root of your dnx solution as in
```
\---DnxApp
    |   global.json
    |
    \---src
        +---app.library1
        |       Class.cs
        |       project.json
        |
        +---app.library2
        |       AnotherClass.cs
        |       project.json
        |
        \---app.web
                Controller.cs
                project.json
```
because it describes the runtime that all the sub projects will use.

**Comment by bitcrazed** [comment] 2015-08-19 21:39
Agreed. Just moved my global.json to what I'd called the solution root - the root of the app as you illustrated above. Still, may be worth looking-up the file's location from the solution in case someone wants to move it for some reason.

**Comment by bitcrazed** [comment] 2015-08-19 21:43
Can also (happily) confirm since moving my global.json, indicating my site runs atop DNX 1.0.0-Beta6, the site now runs as expected (Was seeing a 5xx error previously).

Thanks for your help on this.

**Comment by bstenberg64** [comment] 2015-09-07 16:29
Can also (happily) confirm that creating a global.json with the required runtime in the project root solves the problem. But shouldn't the yeoman generator add a global.json? I'll see if this is addressed. Big thanks for finding the problem though. I was diffing 2 projects created using Visual Studio and yeoman to find the differences but as the layout and contents are different it was a bit daunting... This was much more efficient.

**Comment by roysanchez** [comment] 2015-09-16 18:52
Had the same problem trying to deploy to azure with beta7, the problem was not having the solution as the root directory of the repo, having a structure like this:

```
\---github - root
     | 
     |
     \---Dnx.App
          |  global.json
          |
          +---app.library1
          |       Class.cs
          |       project.json
          |
          \---app.web
                  Controller.cs
                  project.json
```
 
Because the global.json file isn't in the root directory of the repo, kudu doesn't find it and falls back to beta6, my solution was to move the global.json file to the root of the repo.

As @bitcrazed said, it may be good to look for the global.json file instead of expecting a standard position.

**Comment by bstenberg64** [comment] 2015-09-17 17:47
Thx @roysanchez. It seems, just like you suggest, that the problem is not in the generator-aspnet itself but rather in how kudu interprets the project structure in azure. As long as you introduce the added folder structure you're fine. Keep global.json at the top and project.json in the subfolder. If the two files are at the same level they will confuse kudu's build/make process. I have no idea whether this is intended behaviour or a bug but you made my day. And another shout out to @bitcrazed who suggests that one shouldn't expect things to be in one place. Smells like hard-coded paths somewhere which I'm of course guilty of a long time ago.

Anyways, I've successfully deployed from VS Code via GitHub to Azure which was my aim. Thanks for all helping with this issue. What a change from 25 years ago!

**Comment by bitcrazed** [comment] 2015-09-18 21:39
@ahmelsayed Many thanks for taking our feedback on board and committing a fix for this issue :grinning:

**Comment by davidfowl** [comment] 2015-09-19 02:24
The publish issue was fixed in beta8

**Comment by davidebbo** [comment] 2015-09-19 20:34
@davidfowl is beta8 out?

**Comment by davidfowl** [comment] 2015-09-19 20:42
Nope, I mean to say, it will be fixed in beta8 :smile: (it's already fixed in ci builds)

**Closed** 2015-09-30 21:38 UTC
