### ISSUE TITLE
Is there any REST API to delete content of site/wwwroot 

### ISSUE THREAD

**Issue by Ajay-MS** [projectkudu/kudu#2103] opened 2016-08-18 06:13 UTC
Hello Team , 

While deploying zip using 'PUT /api/zip/{path}' , It only override existing content means if some extra file already exists at '{Path}' , it doesn't clean those files. So tried to use REST API corresponding to vsf but it still can only delete a file or able to delete a directory only if its empty , but I have target to clean the content of a directory. So is there any regex I can specify to delete the content of the directory.

**Comment by davidebbo** [comment] 2016-08-18 15:55
It's by design that the zip API doesn't delete any files. It's not an incremental/sync deployment like msdeploy.

I would have thought that the vfs delete API would be able to delete a whole folder and everything in it. Is that failing for you? Can you give more details?

**Comment by Ajay-MS** [comment] 2016-08-19 05:20
@davidebbo 

Yes its failing with following error, I tried to delete a folder 'xyz' inside wwwroot.

```
Invoke-RestMethod : {"Message":"Cannot delete directory. It is either not empty or access is not allowed."}
At E:\WebAppRESTDeployment.ps1:15 char:1
```

But target is not to delete a folder , I want to clean all contents of wwwroot , one way to achieve this is first I will delete wwwroot and then create wwwroot ( This is not currently working also as not able to delete folder ) , but even I am successful to delete wwwroot , I don't think its a good approach for cleaning. 

Can you help what is best approach to clean wwwroot directory using KUDU REST API ?

**Comment by ahmelsayed** [comment] 2016-08-19 18:08
I'd use the [command](https://github.com/projectkudu/kudu/wiki/REST-API#command) api to do that. Craft a CMD or PowerShell command that'll clean your wwwroot and then execute it.

**Comment by davidebbo** [comment] 2016-08-19 18:08
The vsf API is able to delete entire directories. If that doesn't work, it likely means that something is locked and can't be delete. e.g. try using `rd` for the same folder using Kudu Console. It'll probably fail as well. You'll need to figure out what's locking it. You can try stopping the site first.

**Comment by davidebbo** [comment] 2016-08-19 18:10
Closing as there is likely no Kudu issue here.

**Closed by davidebbo** 2016-08-19 18:10 UTC

**Comment by atrauzzi** [comment] 2017-03-19 15:32
Sorry for the necro on this ticket: I've been doing some scripting targeting the same directory and one issue that I'm finding is that the speed of file operations on App Service is so slow that it's becoming next to impossible to automate my own deployments.

In one instance, my delete request times out, so I end up running subsequent commands.  In an attempt to get around this, I thought maybe I could rename the `wwwroot` directory so that I can at least push new files up and queue the delete to complete on its own time.  Sadly, that directory remains locked, whether my app is running or not.

It might be nice to see something a little more concrete in this area as there are quite a few gotchas when working directly with files in App Service and keeping everything clean can be tricky.

**Comment by prebenh** [comment] 2018-10-16 06:03
Here is the Powershell script if you want to recursively delete all files and folders.

<pre><code>
$username = '' #From the publish profile
$password = "" #From the publish profile
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("$($username):$($password)")))

$userAgent = "powershell/1.0"

$apiUrl = "https://somewebapp.scm.azurewebsites.net/api/vfs/site/wwwroot/app_data/jobs/triggered/"

$headers = @{ 
	Authorization="Basic $($base64AuthInfo)"
	'If-Match'      = '*'
}

$triggerdJobs = Invoke-RestMethod -Uri $apiUrl -Headers $headers -UserAgent $userAgent -Method GET -ContentType "application/json"


function DeleteKuduDir ($content)
{
	foreach($c in $content)
	{
		
		if($c.mime -eq "inode/directory")
		{
			Write-Host "Deleting DIRECTORY"
			$childContent = Invoke-RestMethod -Uri $c.href -Headers $headers -UserAgent $userAgent -Method GET -ContentType "application/json"
			
			DeleteKuduDir $childContent
		}
		
		Write-Host "Delete: $($c.href)"
		Invoke-RestMethod -Uri $c.href -Headers $headers -UserAgent $userAgent -Method DELETE -ContentType "application/json"
	}
}

DeleteKuduDir $triggerdJobs
</code></pre>
